"""2위 — 추석 (DdoDhCECm9C): 44.5초, 19샷."""

A = "[CHARACTER] in a children's saekdong hanbok (rainbow-striped sleeves, green jeogori with a red ribbon, blue-red skirt) and a black embroidered traditional cap with a rainbow tassel"
B = "[CHARACTER_2] in a pale pink hanbok with a pink knot hair ornament (norigae style)"
ROOM = "bright modern Korean living room, white boucle sofa, light oak floor, sheer curtains, soft daylight"


def s(i, t0, t1, name, size, angle, move, comp, action, text, sound, out, img, vid, models, note=""):
    return {"id": f"S{i:02d}", "t0": t0, "t1": t1, "name": name, "size": size, "angle": angle, "lens": "",
            "move": move, "comp": comp, "action": action, "bg": "", "light": "", "text": text, "sound": sound,
            "out": out, "img": img, "vid": vid, "models": models, "note": note}


RANK2 = {
    "rank": 2, "id": "DdoDhCECm9C", "file": "rank2.html",
    "title": "추석 가족 — 44.5초 · 19샷",
    "caption": "매일 추석이면 좋겠꾸이",
    "url": "https://www.instagram.com/reel/DdoDhCECm9C/",
    "stats": [("조회수", "8.85만 (업로드 1일차)"), ("좋아요", "5,183"), ("댓글", "84"), ("업로드", "2026-09-23"),
              ("길이", "44.50초"), ("샷", "19 (전환 18)"), ("평균 샷 길이", "2.34초"), ("배경음악", "없음 (클립 소리 이어붙임)")],
    "one_liner": ("세배 → 용돈 → 송편 내기 → 대형 송편 → 명절 상 → 갈비찜 → '매일 추석이었으면'. 명절 체크리스트를 "
                  "캐릭터 가족극으로 44초에 압축. 아이들은 '꾸이'로만 말하고 뜻은 한·영·일 3줄 자막이 전달."),
    "structure_note": ("⚠️ 업로드 1일차 영상이라 점수(하루 평균)가 부풀려져 있습니다. 조회수 규모는 4위(78.8만) 이하 — "
                       "검증된 흥행작이라기보다 '시즌 템플릿'으로 참고하세요. 분석 중 자동 감지가 놓친 숨은 전환 4개(3.70·20.40·29.25·30.80초)를 "
                       "프레임 단위로 확인해 15샷 → 19샷으로 보정했습니다."),
    "viral": [
        ("0.0–2.1초", "시즌 훅", "한복 입은 두 캐릭터의 세배. 명절 직전 업로드 → 알고리즘이 시즌 키워드와 함께 밀어줌."),
        ("2.1–5.7초", "작은 갈등", "누나(또리)가 절을 계속하자 꾸이가 어깨를 톡 — '절은 한 번만'. 생활 개그로 공감."),
        ("5.7–10.7초", "보상 = 용돈", "아빠의 5만원 뭉치 → 휙(휩 팬) → 반짝 눈. 명절의 가장 짜릿한 순간을 1초 반응샷으로."),
        ("10.7–27.3초", "미니 대결 서사", "송편 내기 → 또리는 토끼 송편(벚꽃 효과) vs 꾸이는 반죽 실패 → '차라리 대형' → 거대 송편. 노력 vs 스케일 개그."),
        ("27.3–29.3초", "리액션 + 시간 점프", "또리의 '저게 뭐지…?' 멍한 표정 → 흰 플래시(0.45초)로 시간 경과."),
        ("29.3–42.2초", "음식 포르노", "명절 상 풀샷 → 반짝 눈 → 엄마의 갈비찜 → 푸시인 → 먹방 클로즈업 2컷(속마음 괄호 자막)."),
        ("42.2–44.5초", "소원 엔딩", "'매일 추석이었으면 좋겠다' = 시청자 마음을 대신 말해 주는 공감 마무리 → 좋아요·공유."),
        ("전체", "3개 언어 자막 + 꾸이어", "아이들은 '꾸이'만 말하고 자막이 뜻을 전달(한·영·일) → 어느 나라에서 봐도 이해. 어른(아빠·엄마)만 실제 한국어 → 대비 개그."),
        ("전체", "반복 모티프: 반짝 눈", "돈(8.3초)·음식(30.8·34.0·42.2초)에서 같은 별빛 눈 → 감정 신호를 학습시킴."),
    ],
    "cast": [
        ("[CHARACTER] (꾸이 역)", "주인공. 색동 한복 + 검정 자수 모자(무지개 술)"),
        ("[CHARACTER_2] (또리 역)", "형제. 연분홍 한복 + 분홍 매듭 머리장식. 원본은 흑백 기니피그"),
        ("[MOM]", "같은 종 어른. 모브색 꽃무늬 니트 가디건 + 레이스 앞치마"),
        ("[DAD]", "같은 종 어른. 파란 반다나 + 빨간 지퍼 플리스 재킷"),
    ],
    "shots": [
        s(1, 0.0, 2.133, "세배", "WS 풀샷(두 캐릭터)", "아이레벨", "고정",
          "좌우 대칭, 두 캐릭터가 화면 중앙 하단, 뒤에 흰 소파 가로선, 바닥이 하단 1/3",
          "두 손을 배에 모으고 깊이 절(머리가 바닥까지) 후 일어남", "엄마, 아빠. 풍성한 한가위 보내세요!",
          "아이들 합창 '꾸이 꾸이 꾸이 꾸이'", "하드컷",
          f"{A} stands on the left and {B} on the right in a {ROOM}; both hold paws together at the belly facing the camera, full body, eye-level wide shot, 35mm, symmetrical composition",
          "Both characters perform a deep Korean bow (sebae) until their heads nearly touch the floor, then rise. Static camera. Tiny squeaky voices chant 'kkui kkui kkui kkui'.",
          ["klingomni", "seedance25"], "두 캐릭터 동시 동작 → 레퍼런스 2장(캐릭터 시트 A·B) 넣기"),
        s(2, 2.133, 3.7, "절 계속하는 또리", "CU", "살짝 부감", "고정",
          "캐릭터2 얼굴 중앙, 머리장식이 상단 1/3", "고개 숙인 채 → 왼쪽에서 앞발이 어깨를 톡 → 놀라서 눈 동그랗게",
          "없음", "작은 놀람 소리", "하드컷",
          f"close-up of {B} with head bowed low and eyes closed, seen slightly from above, blurred {ROOM} background, 50mm, shallow depth of field",
          "She stays bowed; a small paw enters from the left and taps her shoulder; she lifts her head with wide surprised eyes. Static camera.",
          ["klingomni", "seedance25"]),
        s(3, 3.7, 5.733, "'절은 한 번만'", "MCU", "아이레벨", "고정",
          "캐릭터 중앙 약간 좌, 오른쪽 가장자리에 캐릭터2 어깨 일부", "캐릭터2 어깨에 손을 얹고 가르치는 무표정",
          "절은 한 번만 하는거야.", "'꾸이 꾸이'", "하드컷",
          f"medium close-up of {A} with one paw on the shoulder of [CHARACTER_2] at the right edge, smug deadpan know-it-all face, eye level, 50mm",
          "He pats her shoulder twice and talks with a smug deadpan face (mouth moving), slight head tilt. Static camera. Squeaky 'kkui kkui'.",
          ["klingomni", "seedance25"]),
        s(4, 5.733, 8.3, "아빠의 용돈", "MS 투샷(부모)", "아이레벨", "고정 → 끝에 지폐가 렌즈로 날아옴",
          "엄마 좌, 아빠 우(화면 중앙 우측). 지갑·지폐가 화면 하단 중앙", "아빠가 지갑에서 5만원 뭉치를 꺼내 내밈 → 끝에 렌즈 쪽으로 휙",
          "그래. 10만원씩 나눠 가져라.", "아빠 실제 한국어 대사(따뜻한 중저음)", "휩 팬 0.2초",
          f"medium shot of [MOM] (mauve floral knit cardigan over a lace apron) on the left and [DAD] (blue patterned bandana, red zip-up fleece jacket) on the right holding a black leather wallet, warm smiles, {ROOM}, eye level, 35mm",
          "[DAD] pulls a thick stack of banknotes from the wallet and holds it toward the camera saying in Korean '그래, 십만원씩 나눠 가져라' in a warm fatherly voice; at the end he flicks the money at the lens with fast motion blur. Static camera.",
          ["veo31", "seedance25"], "한국어 대사 립싱크 → Veo 3.1. 대안: TTS(ElevenLabs v3)로 더빙. ⚠️ 지폐는 실물과 다른 소품 디자인으로"),
        s(5, 8.3, 10.733, "용돈 반짝 눈", "MCU 투샷", "아이레벨", "휩 인(0.2초) 후 고정",
          "두 캐릭터가 화면을 좌우로 채움, 지폐 부채가 가슴 높이", "지폐를 부채처럼 펼치고 눈이 별빛으로 반짝, 입 벌리고 환호",
          "용돈이다~~!", "'꾸이!'", "휩 팬 0.2초",
          f"{A} and {B} side by side, each holding a fan of banknotes at chest height, eyes sparkling with star-shaped glints, open-mouth joyful smiles, bright bokeh, eye level, 50mm",
          "Both fan the banknotes; their eyes turn into twinkling star highlights; they squeal 'kkui!' and bounce slightly. Static camera.",
          ["klingomni", "seedance25"], "별빛 눈은 프롬프트로 생성(원본도 영상 안에 있음). 편집 이펙트 대체 가능"),
        s(6, 10.733, 13.7, "송편 내기", "WS", "아이레벨", "휩 인 후 고정",
          "테이블이 하단 절반(떡 반죽 쟁반·소 그릇), 캐릭터 둘이 상단 중앙", "캐릭터2가 내기를 제안 → 캐릭터 '좋아!'",
          "우리 송편 누가 더 잘 빚나 내기할래? / 좋아!", "'꾸이 꾸이 꾸이 꾸이' / '꾸이!'", "줌 블러 0.2초",
          f"wide shot across a low wooden table with pastel songpyeon dough balls (white, pink, mint, yellow) on a round wooden tray with pine needles and small bowls of black sesame, red bean and soybean powder; {A} and {B} sit behind the table; {ROOM}; eye level, 28mm",
          "[CHARACTER_2] points at the dough and proposes a contest ('kkui kkui kkui kkui'); [CHARACTER] nods and answers 'kkui!'. Static camera.",
          ["klingomni", "seedance25"]),
        s(7, 13.7, 16.267, "토끼 송편 (또리 승)", "CU", "아이레벨", "줌 블러 인 후 고정",
          "캐릭터2 중앙, 토끼 송편이 가슴 높이 중앙", "토끼 얼굴 송편을 자랑스럽게 들고 새침한 미소",
          "없음", "반짝 효과음(추정)", "블러 휩 0.2초",
          f"close-up of {B} proudly holding a white rice cake shaped like a cute bunny face with pink cheeks at chest height, smug closed-mouth smile, soft pink glow and floating cherry blossom petals, dreamy pastel background",
          "She lifts the bunny songpyeon slightly and smiles smugly; cherry blossom petals drift and sparkle around her. Static camera.",
          ["klingomni", "seedance25"], "벚꽃·글로우는 편집 오버레이(CapCut '벚꽃'·'반짝이')로 넣어도 됨"),
        s(8, 16.267, 20.4, "반죽 실패 → 실망한 얼굴", "MCU(목 아래) → 틸트 업", "아이레벨", "고정 → 19~20초 틸트 업",
          "처음엔 손과 반죽만(얼굴은 프레임 밖) → 틸트 업으로 얼굴 공개", "반죽을 들어 올리면 쭉 늘어나다 철퍼덕 → 처진 눈",
          "없음", "반죽 찍찍·철퍼덕 폴리", "하드컷(점프 인)",
          f"close-up at table level of the tiny paws of {A} pressing into a flattened sticky white rice dough on a floured dark wooden board, hanbok chest visible at the top, face cropped out of frame, 50mm",
          "The paws lift the sticky dough, which stretches into long gooey strings and collapses into a flat messy pancake. The camera then slowly tilts up to reveal his disappointed face with drooping eyes. Realistic dough physics.",
          ["minimaxh3", "klingomni"], "반죽 물리 → MiniMax H3"),
        s(9, 20.4, 21.733, "'차라리 대형 송편'", "ECU 얼굴", "아이레벨", "고정",
          "얼굴이 화면 가득(모자~턱), 입이 하단 1/3", "무표정으로 결심하듯 말함",
          "차라리 대형 송편을 만들자.", "'꾸이'", "하드컷",
          f"extreme close-up of the face of {A} from the cap to the chin, deadpan determined eyes, lips slightly parted, soft living-room light",
          "He speaks with a flat, determined deadpan expression, tiny nod. Static camera.", ["klingomni", "seedance25"]),
        s(10, 21.733, 24.967, "반죽 합체 (타임랩스)", "인서트 CU", "살짝 부감", "고정",
          "나무판 위 작은 반죽 여러 개 → 하나로", "앞발로 작은 반죽들을 모아 빠르게 치대 큰 덩어리로",
          "없음", "치대는 소리", "하드컷",
          "close-up of a floured wooden board with a dozen small white rice dough balls; tiny paws in rainbow-striped hanbok sleeves gathering them",
          "The paws push all the small dough balls together and knead them into one huge smooth dough mound, time-lapse speed. Static camera.",
          ["minimaxh3", "seedance25"]),
        s(11, 24.967, 27.3, "대형 송편 완성", "MCU", "아이레벨", "고정",
          "캐릭터 중앙, 거대 송편이 화면 하단 절반", "몸통보다 큰 송편을 들고 앞니 보이며 뿌듯한 웃음",
          "대형 송편 완성이다 꾸이~~!", "'꾸이 꾸이, 꾸이!!'", "하드컷",
          f"medium close-up of {A} hugging a giant white songpyeon larger than his torso, proud toothy grin showing buck teeth, bright background, eye level",
          "He lifts the giant songpyeon proudly and grins, triumphant squeak 'kkui kkui, kkui!!'. Static camera.",
          ["klingomni", "seedance25"]),
        s(12, 27.3, 29.25, "'저게 뭐지…?'", "CU", "아이레벨", "고정",
          "캐릭터2 중앙, 전경 좌측에 흐린 거대 송편", "작은 잎 장식 송편을 든 채 거대 송편을 멍하니 봄",
          "저게 뭐지....?", "'꾸이?'", "흰 플래시 0.45초(시간 경과)",
          f"close-up of {B} holding a small elegant songpyeon decorated with a green leaf, staring wide-eyed at a giant white songpyeon out of focus in the left foreground",
          "Her eyes widen slowly, stunned, mouth slightly open, a tiny puzzled squeak 'kkui?'. Static camera.",
          ["klingomni", "seedance25"]),
        s(13, 29.25, 30.8, "명절 상 풀샷", "WS", "아이레벨", "고정",
          "긴 좌식 상이 하단, 캐릭터 둘 상단 중앙 대칭, 창문 빛", "음식을 바라봄",
          "없음", "잔잔한 실내음", "점프 컷(가까이)",
          f"wide shot of {A} and {B} sitting behind a long low table full of Chuseok dishes: assorted jeon, meatballs, namul, bowls of clear soup, colorful songpyeon; bright window light, sheer curtains, eye level, 28mm, symmetrical",
          "Both look over the feast, heads turning slightly. Static camera.", ["omni11", "klingomni"]),
        s(14, 30.8, 32.1, "'맛있겠다~~!'", "MS", "아이레벨", "고정",
          "두 캐릭터 상반신, 전경에 전 접시", "별빛 눈으로 활짝 웃음",
          "맛있겠다~~!", "'꾸이 꾸이'", "디졸브 0.1초",
          f"medium shot of {A} and {B} behind the feast, eyes glowing with star-shaped sparkles, huge smiles, jeon platter in the foreground",
          "Their eyes sparkle and they cheer 'kkui kkui!' happily. Static camera.", ["klingomni", "seedance25"]),
        s(15, 32.1, 34.0, "엄마의 갈비찜", "MCU", "아이레벨", "고정",
          "엄마 중앙, 냄비가 화면 하단 1/3을 가로로 채움", "큰 냄비를 카메라 쪽으로 내밀며 말함",
          "갈비찜 나간다, 얘들아~", "엄마 실제 한국어 대사", "하드컷",
          "medium close-up of [MOM] (mauve floral knit cardigan, lace apron) holding a large cream enamel Dutch oven full of glossy braised short ribs with carrots, chestnuts and jujubes toward the camera, warm smile, modern kitchen background, eye level, 50mm",
          "She presents the pot toward the camera and says in Korean '갈비찜 나간다, 얘들아~' in a cheerful motherly voice; steam rises. Static camera.",
          ["veo31", "seedance25"], "한국어 대사 → Veo 3.1 또는 TTS 더빙"),
        s(16, 34.0, 36.333, "상에 올린 갈비찜 → 푸시인", "WS → CU(음식)", "아이레벨", "슬로 푸시인",
          "냄비가 전경 중앙, 뒤에 반짝 눈 캐릭터 둘", "환호 → 카메라가 윤기 나는 갈비로 다가감",
          "없음", "'꾸이 꾸이'", "하드컷",
          f"wide shot: the galbi-jjim pot on the table in front of {A} and {B}, both with star-sparkle eyes and open-mouth excitement",
          "The camera slowly pushes in from the two characters to a mouth-watering close-up of the glossy short ribs, steam rising, sauce glistening.",
          ["omni11", "veo31"], "음식 클로즈업 화질 → Omni 1.1 Flash(4K)·Veo 3.1"),
        s(17, 36.333, 40.033, "갈비 먹방", "MCU", "아이레벨", "고정",
          "캐릭터 중앙, 갈비가 입 높이, 전경에 냄비", "갈비를 물어뜯고 눈 감고 음미",
          "(입에서 살살 녹는다 꾸이...)", "먹는 소리(ASMR)", "블러 0.15초",
          f"medium close-up of {A} holding a braised short rib with both paws near his mouth, wide eyes, pot of galbi-jjim in the foreground",
          "He bites the tender rib, meat pulls off the bone, his eyes close in bliss as he chews slowly. Static camera.",
          ["klingomni", "seedance25"], "괄호 자막 = 속마음 표현"),
        s(18, 40.033, 42.2, "전 먹방", "MCU", "아이레벨", "고정",
          "캐릭터2 중앙, 반쯤 먹은 전이 가슴 높이", "무표정으로 천천히 씹음",
          "(맛있다 꾸이...)", "씹는 소리", "가로 늘이기 휩 0.15초",
          f"medium close-up of {B} holding a half-eaten golden jeon with green onion, deadpan satisfied face, namul in the foreground",
          "She chews slowly with a deadpan blissful face. Static camera.", ["klingomni", "seedance25"]),
        s(19, 42.2, 44.5, "소원 엔딩", "MS 투샷", "아이레벨", "슬로 푸시인",
          "두 캐릭터 좌우, 전경에 갈비", "별빛 눈 + 앞니 드러낸 큰 웃음으로 카메라 응시",
          "매일 추석이었으면 좋겠다 꾸이!!!", "'꾸이 꾸이 꾸이'", "영상 끝",
          f"medium shot of {A} holding a short rib and {B} holding a jeon side by side behind the feast, both with star-sparkle eyes and huge toothy smiles",
          "Both look at the camera with sparkling eyes and cheer 'kkui kkui kkui!'; slow push-in.", ["klingomni", "seedance25"]),
    ],
    "gen_plans": [
        ("추천 조합", "캐릭터 컷 14개 = Kling v3 Omni(레퍼런스→영상, 캐릭터 시트 4장) · 대사 컷 2개(S04·S15) = Veo 3.1 · 물리 컷 2개(S08·S10) = MiniMax H3 · 음식 컷(S13·S16) = Omni 1.1 Flash",
         "모든 컷을 5초로 생성 후 EDL이 필요한 구간만 잘라 씀. 컷마다 첫 프레임 이미지(샷 카드의 이미지 프롬프트)를 먼저 만들 것.",
         "키프레임 19장 × 9 + 영상 19개 × 20~48 (할인가) ≈ 약 600~900 × 재시도"),
    ],
    "transitions": [
        {"t": "8.30초", "type": "휩 팬 (가로 모션블러)", "frames": "3~4프레임", "how": "아빠가 돈을 렌즈로 휙 → 가로 블러로 다음 컷",
         "ffmpeg": "xfade=transition=hblur:duration=0.2", "capcut": "전환 > 휙(Swipe)/블러 0.2초", "pro": "Premiere: Whip(Film Impact) 6f / AE: 방향 블러 + 위치 키프레임"},
        {"t": "10.73초", "type": "휩 인 (고스트 스미어)", "frames": "3프레임", "how": "새 컷이 가로로 번진 상태로 시작",
         "ffmpeg": "xfade=transition=hblur:duration=0.2", "capcut": "휙 0.2초", "pro": "Directional Blur 60→0"},
        {"t": "13.70초", "type": "줌 블러", "frames": "2~3프레임", "how": "확대되며 흐려진 뒤 다음 컷(토끼 송편) 공개",
         "ffmpeg": "xfade=transition=zoomin:duration=0.2", "capcut": "줌 인 0.2초", "pro": "AE: 스케일 100→135% + 방사형 블러"},
        {"t": "16.27초", "type": "블러 휩", "frames": "3프레임", "how": "흐림 + 가로 이동",
         "ffmpeg": "xfade=transition=hblur:duration=0.2", "capcut": "블러 0.2초", "pro": "Gaussian Blur 전환"},
        {"t": "29.25초", "type": "흰 플래시 디졸브 (시간 경과)", "frames": "약 13프레임(0.45초)", "how": "밝게 날아갔다가 명절 상으로",
         "ffmpeg": "xfade=transition=fadewhite:duration=0.45", "capcut": "화이트 플래시/화이트아웃 0.45초", "pro": "Dip to White 13f"},
        {"t": "30.80초", "type": "점프 컷(가까이)", "frames": "0", "how": "같은 구도에서 한 단계 가까운 샷으로 툭",
         "ffmpeg": "하드컷", "capcut": "없음(그냥 자르기)", "pro": "Cut"},
        {"t": "32.10초", "type": "짧은 디졸브", "frames": "2~3프레임", "how": "AI 클립 이음새를 부드럽게",
         "ffmpeg": "xfade=transition=fade:duration=0.1", "capcut": "디졸브 0.1초", "pro": "Cross Dissolve 3f"},
        {"t": "40.03초", "type": "블러 전환", "frames": "3프레임", "how": "크게 흐려졌다 선명해짐",
         "ffmpeg": "xfade=transition=hblur:duration=0.15", "capcut": "블러 0.15초", "pro": "Gaussian Blur 전환"},
        {"t": "42.20초", "type": "가로 늘이기 휩", "frames": "3프레임", "how": "얼굴이 옆으로 늘어나며 넘어감",
         "ffmpeg": "xfade=transition=squeezeh:duration=0.15", "capcut": "늘이기/스트레치 0.15초", "pro": "AE: 가로 스케일 100→190%"},
        {"t": "나머지 9곳", "type": "하드 컷", "frames": "0", "how": "2.13·3.70·5.73·20.40·21.73·24.97·27.30·34.00·36.33초 — 대사 컷은 모두 하드컷",
         "ffmpeg": "하드컷(concat)", "capcut": "없음", "pro": "Cut"},
    ],
    "audio": {
        "summary": ("배경음악 없음. 각 AI 클립의 자체 소리(아이들 '꾸이' 목소리·폴리·어른 한국어 대사)를 컷마다 그대로 이어 붙임. "
                    "18개 전환 중 13개가 새 소리 시작점과 정확히 겹침(±70ms) = 오디오도 화면과 같이 '하드컷'. "
                    "컷 사이에 0.2~0.6초 완전 무음이 9번(1.98·2.40·5.01·8.35·13.05·27.78·28.82·30.50·34.78초) → 코믹한 정적. "
                    "-14.7 LUFS / LRA 9.9 / 트루피크 +0.2 dBFS(넘침 → 재현 시 -1 dBTP 리미터)."),
        "cues": [
            ("0.0–6.0", "아이들 '꾸이 꾸이 꾸이 꾸이'", "캐릭터 컷마다 클립 오디오"),
            ("6.0–8.0", "아빠: '그래, 십만원씩 나눠 가져라'", "실제 한국어 대사"),
            ("9.4–10.7", "'꾸이!' 환호", ""),
            ("11.2–12.8", "'꾸이 꾸이 꾸이 꾸이' (내기 제안)", ""),
            ("16.3–21.9", "'꾸이' + 반죽 폴리", ""),
            ("25.2–25.7", "'꾸이 꾸이, 꾸이!!'", ""),
            ("27.6–28.2", "'꾸이?'", ""),
            ("32.2–34.1", "엄마: '갈비찜 나간다, 얘들아'", "실제 한국어 대사"),
            ("43.1–44.5", "'꾸이 꾸이 꾸이'", "엔딩"),
        ],
        "music_prompt": "",
        "sfx_prompts": ["soft sparkle chime, magical twinkle, 1 second (반짝 눈·토끼 송편용 — 선택)",
                        "sticky rice dough stretching and slapping on a wooden board, 3 seconds"],
        "voice": ("아이 캐릭터 = 'kkui'만 반복하는 고음 목소리(영상 모델 오디오 켬). 어른 = 한국어 대사: Veo 3.1 네이티브 대사 또는 "
                  "ElevenLabs v3 / MiniMax Speech 2.8 HD TTS 후 클립에 얹기."),
    },
    "edl": ["edl_rank2_chuseok.json"],
    "hf": ["hyperframes/rank2_chuseok/index.html"],
    "legal": [
        "⚠️ 지폐: 실물 화폐와 똑같은 도안은 피하고 크기·색이 다른 소품 디자인 사용 (한국은행 화폐도안 이용기준 확인 권장)",
        "명절·한복·음식은 보편 소재 → 저작권 위험 낮음. 원작의 대사·자막 문장을 그대로 쓰지 말고 새로 쓰기",
        "인스타 'AI 정보' 라벨 켜기",
    ],
    "enhance": [
        "추석·설날·크리스마스 등 시즌마다 같은 구조(인사→보상→대결→반전→음식→소원)로 복제 가능한 템플릿",
        "무음 갭 9곳은 원본의 우연일 수 있음 → 재현할 땐 0.2초 이하 룸톤을 깔아 '끊김'이 아닌 '정적'으로 들리게",
    ],
}
