"""11~17위 분석 콘텐츠."""
from content_rank4_10 import s, ev, page, CH, LABEL

C2 = "[CHARACTER_2]"
STD = {"kr_size": 58, "en_size": 32, "kr_y": 0.741, "en_dy": 0.036, "jp_dy": 0.06, "jp_size": 28, "outline": 2.4, "shadow": 1.8}
K = ["klingomni", "seedance25"]

RANK11 = page(
    11, "Dazoyz_CHwN", "여름 더위 개그 — 20.6초", "한국 여름 특 ) 꾸이통바베큐구이",
    [("조회수", "240만"), ("좋아요", "118,368"), ("댓글", "388"), ("업로드", "2026-07-15"), ("길이", "20.63초"),
     ("장면", "6"), ("fps", "30"), ("배경음악", "있음")],
    "머리에 불이 붙은 채 걷는 캐릭터 → 빙수 가게에서 김 → 얼음 수영장에서도 햇빛 레이저에 몸이 활활 → 에어컨 풀가동 방이 꽁꽁. '한국 여름'을 과장한 시각 개그.",
    "대사 4줄, 핵심은 '머리 불꽃' 시각 효과. 계절 공감(폭염) + 과장 VFX = 7월 업로드로 시즌 효과.",
    [("0–2.5초", "불타는 머리", "길 한복판에서 머리에서 불길이 솟음 = 첫 1초에 '이게 뭐야' 훅."),
     ("2.5–8초", "빙수로 해결?", "'열 식히러 가야지' → 망고빙수 먹자 머리에서 김 → '이제야 살겠네'."),
     ("8–14.5초", "더 큰 더위", "얼음 수영장+선풍기에도 해가 레이저를 쏴 온몸이 불 → '왜 이렇게 더운거야?!' 에스컬레이션."),
     ("14.5–20.6초", "에어컨 엔딩", "에어컨 바람에 불 꺼지고 방 전체가 얼음·고드름 → '에어컨은 누가 발명했을까?' 감사 엔딩.")],
    [s(1, 0.0, 2.47, "불타는 머리로 걷기", "FS", "고정", "보도 중앙, 도시 거리 배경", "걸어오다 머리에 불이 확", "없음", "화르륵", "하드컷",
       f"{CH} standing on a sunny city sidewalk in summer, trees and shops behind, full body, eye level", "Flames suddenly burst from the top of its head as it waddles forward, heat haze. Static camera.", ["minimaxh3", "seedance25"], "불·연기 VFX → MiniMax H3"),
     s(2, 2.47, 4.43, "빙수 가게 앞 → 입장", "MS", "고정", "가게 간판 아래 캐릭터", "손 흔들고 가게로 들어감", "열 식히러 가야지", "", "하드컷",
       f"{CH} with flames on its head standing in front of a shaved-ice dessert shop (fictional sign)", "It waves and walks into the shop. Static camera.", K, LABEL + " (설빙 간판)"),
     s(3, 4.43, 8.0, "빙수 먹고 김 모락", "MS", "고정", "테이블 위 망고빙수, 뒤 카페", "먹자 불이 연기로 바뀜", "이제야 살겠네", "치익", "하드컷",
       f"{CH} sitting at a cafe table eating mango shaved ice (bingsu), flames on its head", "As it eats, the flames turn into white steam clouds; relieved face. Static camera.", ["seedance25", "minimaxh3"]),
     s(4, 8.0, 14.5, "얼음 수영장 + 햇빛 레이저", "MS", "고정", "잔디밭 위 파란 풀장, 앞 선풍기, 위 해", "해가 레이저를 쏴 몸 전체에 불",
       "왜 이렇게 더운거야?!", "화르륵·비명", "하드컷",
       f"{CH} sitting in an inflatable pool full of ice cubes on a green field under a blazing sun, a big electric fan in front", "The sun shoots a heat beam; its whole body bursts into flames and it screams with arms up. Static camera.", ["minimaxh3", "seedance25"]),
     s(5, 14.5, 18.5, "에어컨 풀가동", "WS", "고정", "분홍 침실, 위 에어컨, 침대 중앙", "에어컨 바람에 불이 꺼짐", "에어컨은 누가 발명했을까?", "바람 소리", "하드컷",
       f"{CH} lying in a pink princess bed with flames on its head under a wall air conditioner blowing cold air", "Cold air blasts, the flames go out into steam, it smiles blissfully. Static camera.", K),
     s(6, 18.5, 20.63, "방이 꽁꽁", "WS", "고정", "같은 구도, 방 전체 성에·고드름", "방이 얼어붙음", "없음", "쩡", "영상 끝", "", "Frost and icicles spread over the whole room. Static camera.", ["minimaxh3"])],
    [ev(2.5, 3.5, "열 식히러 가야지", "Time to cool off!"), ev(7.0, 8.3, "이제야 살겠네", "Finally, that's better."),
     ev(13.4, 14.3, "왜 이렇게 더운거야?!", "Why is it so hot?!"), ev(16.8, 18.2, "에어컨은 누가 발명했을까?", "Who invented the air conditioner?")],
    STD,
    {"summary": "배경음악 + 불·김·바람 효과음 중심. (측정 수치는 아래 이미지)", "cues": [("0–20.6", "여름 BGM + 불/바람 효과음", "")],
     "music_prompt": "Suno v5.5 — upbeat quirky summer comedy BGM, 120 BPM, ukulele and brass stabs, 21 seconds, instrumental",
     "sfx_prompts": ["fire whoosh igniting, 1 second", "cold air conditioner blast and ice freezing crackle, 3 seconds"], "voice": "캐릭터 '꾸이' + 자막"},
    [("추천", "불·얼음 VFX 컷 = MiniMax H3 · 캐릭터 연기 = Kling v3 Omni", "머리 불꽃은 모든 컷에서 같은 위치로 — 레퍼런스에 불꽃 넣은 캐릭터 시트 사용", "약 6컷 ≈ 약 250~400")],
    [LABEL + " (설빙)", "인스타 'AI 정보' 라벨 켜기"], ["겨울판: '한국 겨울 특' — 머리에 고드름"])

RANK12 = page(
    12, "Dc0bTviiDlX", "트러블 → 커버크림 광고 — 38초", "약속 전에 트러블이 나버린 김꾸이ㅠㅠ (협찬)",
    [("조회수", "61만"), ("좋아요", "16,803"), ("댓글", "161"), ("업로드", "2026-09-03"), ("길이", "37.97초"),
     ("컷", "38 (빠른 광고 편집)"), ("fps", "30"), ("배경음악", "있음")],
    "볼 트러블 → 올리브영 택배 도착 → 상자 속으로 → 제품 공개(커버크림·톤업선크림) → 바르기 → 구름 위 둥실 → 토끼들 등장 '체이싱래빗 고마워!'. 캐릭터 IP로 만든 뷰티 브랜드 광고.",
    "⚠️ 유료 광고(협찬) 영상 — 브랜드·제품이 주인공. 재현할 땐 '광고 포맷 템플릿'으로만 참고하고, 실제 광고라면 '유료광고' 표기 필수.",
    [("0–2.5초", "문제 제시", "거울 앞 '피부에 트러블 났어…' = 뷰티 광고 공식(문제→해결)."),
     ("2.5–12초", "언박싱 서스펜스", "택배 → '뭐지?' → 상자에 몸을 밀어 넣음 '영차! 좀만 더!' → '드디어 왔구나!'"),
     ("12–25초", "제품 소개", "패키지 클로즈업 · 발림 매크로 · 퍼프 = 광고 필수 샷."),
     ("25–31초", "효과 = 구름 위", "'뽀송뽀송하다!' 가벼운 느낌을 구름 위 비행으로 시각화."),
     ("31–38초", "브랜드 마스코트 엔딩", "토끼 떼(브랜드 캐릭터) 등장 + 로고 = 브랜드 인지.")],
    [s(1, 0.0, 2.5, "거울 앞 트러블", "MCU", "고정", "화장대 거울 속 캐릭터, 볼에 붉은 트러블", "볼을 만지며 속상", "피부에 트러블 났어...", "", "하드컷",
       f"{CH} looking into a vanity mirror at a pink makeup table, a red blemish on its cheek, sad face", "It touches its cheek sadly. Static camera.", K),
     s(2, 2.5, 6.4, "택배 도착", "WS/CU", "고정", "바닥의 택배 상자, 멀리 캐릭터", "상자를 발견하고 다가옴", "뭐지? / 이게 뭐지?", "", "하드컷",
       f"a cardboard delivery box (fictional beauty-store logo) on a pink floor, {CH} waddling toward it", "It approaches the box curiously.", K),
     s(3, 6.4, 12.0, "상자 속으로", "MS/POV", "고정", "상자 속 시점, 입구로 캐릭터 얼굴", "몸을 밀어 넣어 상자 속으로", "영차! / 좀만 더! / 드디어 왔구나!", "끙끙", "하드컷",
       "", "It squeezes itself into the box, POV from inside the box.", K),
     s(4, 12.0, 17.8, "제품 공개", "CU", "고정/슬라이드", "제품 패키지가 화면 중앙", "제품을 들어 보여줌", "(제품 패키지 그래픽)", "반짝", "하드컷",
       "product close-ups of a cover cream box and a tone-up sunscreen tube (fictional brand) on a pink vanity", "Products slide into frame one by one.", ["omni11", "veo31"], "광고 컷은 실제 제품 사진 합성이 안전"),
     s(5, 17.8, 25.0, "커버크림 바르기", "MCU/매크로", "고정", "크림 텍스처 매크로 → 퍼프", "크림을 볼에 바르고 퍼프로 두드림", "커버크림~!", "", "하드컷",
       "", "Macro: cream texture spread on the cheek with a spatula, then patted with a puff.", ["veo31", "klingomni"]),
     s(6, 25.0, 28.4, "톤업 선크림", "CU", "고정", "튜브를 짜는 손", "선크림을 짜서 바름", "톤업 선크림~!", "", "하드컷", "", "It squeezes sunscreen and pats its face.", K),
     s(7, 28.4, 31.0, "구름 위 둥실", "FS", "고정", "하늘 배경, 구름 위 캐릭터 중앙", "양팔 벌리고 떠다님", "뽀송뽀송하다!", "", "하드컷",
       f"{CH} floating in the blue sky above fluffy clouds with arms spread, blissful", "It floats gently.", ["seedance25"]),
     s(8, 31.0, 34.0, "현관 '오예~'", "MCU", "고정", "분홍 현관 매트 위", "기뻐하며 문을 엶", "오예~~", "", "하드컷", "", "It cheers and opens the door.", K),
     s(9, 34.0, 37.97, "토끼 떼 + 브랜드", "WS→MS", "고정", "문밖에서 흰 토끼 떼가 들어옴, 상단 브랜드 로고", "토끼들과 인사", "얘들아 반가워~! / 체이싱래빗 고마워!", "", "영상 끝",
       f"a flock of fluffy white bunnies hopping through a pink front door around {CH}", "Bunnies surround it; it hugs them.", ["seedance25", "minimaxh3"])],
    [ev(0.7, 2.4, "피부에 트러블 났어...", "I'm breaking out..."), ev(2.75, 3.5, "뭐지?", "What's that?"), ev(4.75, 5.5, "이게 뭐지?", "What is it?"),
     ev(6.5, 7.2, "영차!", "Heave-ho!"), ev(9.0, 10.0, "좀만 더!", "Just a little more!"), ev(11.0, 12.0, "드디어 왔구나!", "You're finally here!"),
     ev(18.0, 18.8, "커버크림~!", "Cover cream~!"), ev(25.0, 25.8, "톤업 선크림~!", "Tone-up sunscreen~!"),
     ev(29.2, 30.8, "뽀송뽀송하다!", "So smooth!"), ev(31.4, 32.3, "오예~~", "Oh yeah~~"), ev(36.0, 36.75, "얘들아 반가워~!", "Nice to see you~!"),
     ev(36.75, 37.9, "체이싱래빗 고마워!", "Thank you, Chasin' Rabbits!")],
    {**STD, "kr_y": 0.70},
    {"summary": "경쾌한 광고 BGM 전체. 효과음(반짝·퍼프)으로 제품 컷 강조.", "cues": [("0–38", "광고 BGM", "")],
     "music_prompt": "Suno v5.5 — bright bubbly K-beauty commercial jingle, 118 BPM, plucky synths and claps, 38 seconds, instrumental",
     "sfx_prompts": ["magical sparkle chime for a product reveal, 1 second"], "voice": "캐릭터 '꾸이'"},
    [("추천", "캐릭터 = Kling v3 Omni · 제품·텍스처 = 실제 제품 사진/촬영 합성 + Veo 3.1", "광고주 제품 이미지를 레퍼런스로 넣어 패키지 모양 보존", "약 9비트 ≈ 약 400~600")],
    ["⚠️ 협찬 광고 — 실제 브랜드명·로고(올리브영·체이싱래빗)를 쓰려면 광고 계약 필요, '유료광고 포함' 표기 의무", "화장품 광고 문구는 효능 과장 금지(화장품법)"],
    ["캐릭터 IP로 광고 수주하는 포맷의 교과서: 문제 → 언박싱 → 제품 → 효과 시각화 → 브랜드 엔딩"])

RANK13 = page(
    13, "Dcnot5XCXqM", "김꾸이의 시간여행 — 57.7초", "김꾸이의 시간여행",
    [("조회수", "140만"), ("좋아요", "22,615"), ("댓글", "157"), ("업로드", "2026-08-29"), ("길이", "57.67초"),
     ("컷", "46"), ("fps", "30"), ("배경음악", "있음 (시네마틱)")],
    "밤 공원의 포털 → 공룡 시대(티라노 추격) → 원시시대(원시인 추격·동굴벽화) → 조선 궁궐(수라상·'누가 만들었느냐!'·'잡아라!') → 미래 도시(로봇 추격) → 공원으로 복귀 '살았다…'.",
    "4개 시대를 같은 구조(도착→위기→추격→포털 탈출)로 반복하는 옴니버스. 가장 길지만 시대가 바뀔 때마다 새 볼거리가 생겨 이탈이 적은 구성.",
    [("0–6초", "포털 훅", "공원에 빛나는 원형 포털 → '뭐지?' → 빨려 들어감."),
     ("6–19초", "공룡", "거대 브라키오 → 티라노 추격 → 포털."),
     ("20–30초", "원시시대", "원시인 창 들고 추격 → 동굴벽화에 꾸이 → '집 보내줘…'."),
     ("32–47초", "조선 궁궐", "왕 '맛이 없다!' → '누가 만들었느냐!' → 궁녀 '저 녀석이 만들었습니다!' → '제가요?' → '잡아라!' 드라마 패러디."),
     ("48–55초", "미래 도시", "자기부상열차·로봇 경찰 '체포하라!'."),
     ("55–57.7초", "귀환", "공원으로 돌아와 '살았다…'.")],
    [s(1, 0.0, 1.5, "밤 공원", "FS", "고정", "밤 공원 길 중앙", "걸어옴", "없음", "", "하드컷", f"{CH} on a park path at night under street lamps", "It waddles forward.", K),
     s(2, 1.5, 6.0, "포털 발견", "WS/CU", "고정", "뒷모습 + 빛나는 원형 포털", "포털을 만지며 빨려 들어감", "뭐지?", "웅웅", "휩", "", "A glowing blue ring portal hums; it touches it and gets pulled in.", ["seedance25", "minimaxh3"]),
     s(3, 6.0, 17.5, "공룡 시대", "다수", "추격 핸드헬드", "정글·호수, 거대 공룡", "공룡 등장 → 티라노 추격", "어디지?", "쿵·포효", "포털",
       f"{CH} in a prehistoric jungle with a huge long-necked dinosaur by a lake, cinematic", "A T-rex roars and chases it through ferns; handheld chase.", ["minimaxh3", "seedance25"]),
     s(4, 17.5, 20.5, "포털 이동", "CU", "회전", "소용돌이 포털 속", "빨려 들어감", "없음", "쉬익", "휩", "", "It spins through a swirling blue vortex.", ["minimaxh3"]),
     s(5, 20.5, 30.0, "원시시대", "다수", "추격", "사막 협곡, 원시인 무리", "원시인 추격 → 동굴 벽화 발견", "집 보내줘...", "함성", "포털",
       f"{CH} in a stone-age canyon chased by cavemen with spears; later in a cave with a primitive wall painting of a guinea pig", "Chase, then it hides in a cave.", ["minimaxh3", "seedance25"]),
     s(6, 30.0, 32.3, "우주 소용돌이", "그래픽", "회전", "은하 소용돌이", "시공간 이동", "없음", "", "디졸브", "", "A cosmic swirl with asteroids.", ["minimaxh3"]),
     s(7, 32.3, 47.3, "조선 궁궐", "다수", "고정", "궁궐 대청, 왕·궁녀들", "왕이 음식 맛보고 분노 → 궁녀가 지목 → 추격",
       "맛이 없다! / 누가 만들었느냐! / 저 녀석이 만들었습니다! / 제가요? / 저 녀석을 잡아라! / 나 아니에요!", "한국어 대사", "포털",
       f"{CH} dressed as a Joseon palace maid (white apron, teal jacket) in a royal hall with a king in red robes eating from a banquet table", "The king tastes food and shouts; maids point at the character; guards chase it with torches.", ["veo31", "seedance25"], "사극 대사 → Veo 3.1"),
     s(8, 47.3, 55.0, "미래 도시", "다수", "추격", "네온 미래 도시, 자기부상열차, 로봇", "로봇 경찰 추격", "체포하라! 체포하라!", "레이저", "포털",
       f"{CH} in a futuristic city with flying cars and a maglev train, white police robots chasing", "Robots chase it, lasers flash.", ["minimaxh3", "seedance25"]),
     s(9, 55.0, 57.67, "귀환", "ECU", "고정", "얼굴 클로즈업", "안도", "살았다...", "", "영상 끝", "", "Back in the park, it sighs in relief, extreme close-up.", K)],
    [ev(2.2, 3.0, "뭐지?", "What is this?"), ev(9.7, 10.3, "어디지?", "Where am I?"), ev(28.0, 28.8, "집 보내줘...", "I wanna go home..."),
     ev(35.7, 36.5, "맛이 없다!", "It tastes terrible!"), ev(38.0, 38.6, "누가 만들었느냐!", "Who made this?!"),
     ev(38.75, 40.3, "저 녀석이 만들었습니다!", "That one did!"), ev(41.75, 43.3, "제가요?", "Me?"),
     ev(43.5, 45.75, "저 녀석을 잡아라!", "Catch her!"), ev(45.75, 46.3, "나 아니에요!", "It wasn't me!"),
     ev(52.5, 53.5, "체포하라! 체포하라!", "Arrest her!"), ev(57.0, 57.67, "살았다...", "I'm saved...")],
    {**STD, "kr_y": 0.752},
    {"summary": "시네마틱 BGM(시대마다 분위기 전환) + 포털 효과음. 조선 파트만 한국어 대사.", "cues": [("0–57.7", "시네마틱 BGM", ""), ("35–47", "사극 대사", "")],
     "music_prompt": "Suno v5.5 — epic comedic adventure orchestral score, 110 BPM, changes flavor per era: primal drums, Korean traditional gayageum, futuristic synth, 58 seconds, instrumental",
     "sfx_prompts": ["sci-fi portal opening whoosh and hum, 2 seconds", "T-rex roar close, 2 seconds"], "voice": "왕·궁녀 = Veo 3.1 사극 한국어 대사"},
    [("추천", "스펙터클(공룡·포털·미래) = MiniMax H3 · 사극 대사 = Veo 3.1 · 캐릭터 = Kling v3 Omni", "시대별로 5초 × 3~4컷. 포털 컷을 공통 전환으로 재사용하면 제작비 절감", "약 20컷 ≈ 약 700~1,000")],
    ["실존 사극·영화 장면을 그대로 베끼지 말 것", "인스타 'AI 정보' 라벨 켜기"], ["시리즈화: 시대 하나당 한 편으로 쪼개 5부작"])

RANK14 = page(
    14, "DbVI4YICk0g", "감기몸살 간호 커플 — 31.8초", "꾸이의 감기몸살…",
    [("조회수", "140만"), ("좋아요", "66,302"), ("댓글", "392"), ("업로드", "2026-07-28"), ("길이", "31.77초"),
     ("컷", "15"), ("fps", "30"), ("배경음악", "있음")],
    "아픈 꾸이가 남자친구(안경·체크셔츠 기니피그)에게 전화 '약 좀 사다줘 자기야…' → 남친 약국·비빔밥집 달려감 → 양손 가득 도착 → 떡볶이 먹으며 '다 나았당~!' → 남친 허탈.",
    "커플 콘텐츠. 남친 대사는 노란 자막, 꾸이는 흰 자막 → 색으로 화자 구분. 집(분홍)과 거리(회색)를 교차 편집해 통화 장면을 표현.",
    [("0–3초", "아픈 꾸이", "얼음주머니·휴지 더미 = 아픔을 한눈에."),
     ("3–14.5초", "교차 통화", "집 ↔ 거리 교차 컷 + '뭐라고?!!!!' 남친 클로즈업 = 통화 드라마."),
     ("14.5–25초", "헌신 몽타주", "약국 '텐텐도 주세요!' · 비빔밥 포장 = 남친의 헌신."),
     ("25–31.8초", "반전 엔딩", "떡볶이 먹으며 '다 나았당~!' → 남친 허탈 = 커플 공감 개그 → 태그 유도.")],
    [s(1, 0.0, 3.0, "아픈 꾸이", "MCU", "고정", "분홍 침대, 얼음주머니, 휴지", "기침·신음", "감기... / 아파...", "콜록", "하드컷",
       f"{CH} lying in a pink floral bed with a blue ice pack on its head, crumpled tissues around, sick face", "It coughs weakly. Static camera.", K),
     s(2, 3.0, 4.5, "남친 걷기", "FS", "고정", "골목 중앙", "걸어옴", "없음", "", "하드컷",
       "a chubby anthropomorphic guinea-pig boyfriend character with human-like black hair and round glasses, wearing a plaid flannel shirt, walking down a sunny residential street", "He walks toward camera.", K, "남친 = [CHARACTER_2] 설정 변경"),
     s(3, 4.5, 14.5, "교차 통화", "교차", "고정", "집 ↔ 거리 교차", "콧물 풍선 → 통화 → 남친 놀람", "(에취!) / 나 아무래도 / 몸살감기 걸린 것 같아 / 뭐라고?!!!! / 약 좀 사다줘 자기야...",
       "대사", "하드컷", "", "Cross-cut phone call: she sneezes with a snot bubble; he stops and gasps in shock (close-up).", K),
     s(4, 14.5, 22.5, "약국", "MS", "고정", "약국 카운터", "약 사기", "텐텐도 주세요!", "", "하드컷",
       "the boyfriend character at a pharmacy counter buying medicine from a pharmacist", "He points at vitamins and buys medicine.", ["veo31", "klingomni"], LABEL + " (텐텐 등 실제 상품)"),
     s(5, 22.5, 25.0, "비빔밥 포장", "WS", "고정", "식당 앞/카운터", "포장 음식 받기", "없음", "", "하드컷", "", "He picks up takeout bags.", K),
     s(6, 25.0, 27.0, "양손 가득 도착", "FS", "고정", "방문 앞", "봉투 들고 뛰어 들어옴", "자기야!", "", "하드컷", "", "He rushes in holding bags.", K),
     s(7, 27.0, 29.3, "떡볶이 먹는 꾸이", "MS", "고정", "침대 옆 떡볶이", "멀쩡하게 떡볶이 먹음", "다 나았당~!", "", "하드컷",
       f"{CH} with an ice pack sitting up happily eating spicy tteokbokki at a bedside table", "She eats happily, totally fine.", K),
     s(8, 29.3, 31.77, "남친 허탈", "CU", "고정", "남친 얼굴", "허탈한 표정", "없음", "", "영상 끝", "", "Close-up of his speechless face.", K)],
    [ev(0.25, 1.8, "감기...", "Cold..."), ev(2.0, 2.8, "아파...", "I feel sick..."), ev(4.75, 5.5, "(에취!)", "(Achoo!)"),
     ev(8.25, 8.8, "나 아무래도", "I think"), ev(9.75, 10.5, "몸살감기 걸린 것 같아", "I caught a bad cold"),
     ev(12.0, 12.5, "뭐라고?!!!!", "What?!!!"), ev(12.5, 14.75, "약 좀 사다줘 자기야...", "Babe, can you get me some medicine..."),
     ev(19.25, 20.0, "텐텐도 주세요!", "Ten Ten too, please!"), ev(28.5, 29.5, "다 나았당~!", "I'm all better~")],
    STD,
    {"summary": "잔잔한 BGM + 대사. 남친 대사 자막은 노란색으로 화자 구분.", "cues": [("0–31.8", "BGM", "")],
     "music_prompt": "Suno v5.5 — sweet cozy rom-com BGM, 95 BPM, soft piano and glockenspiel, 32 seconds, instrumental",
     "sfx_prompts": ["cute sneeze with a snot bubble pop, 1 second"], "voice": "두 캐릭터 모두 '꾸이' 계열 소리 + 자막"},
    [("추천", "두 캐릭터 = Kling v3 Omni(레퍼런스 2장) · 약사 = Veo 3.1", "노란 자막 = EDL/HyperFrames에서 남친 대사만 색 변경(PrimaryColour)", "약 8비트 ≈ 약 300~450")],
    [LABEL + " (텐텐 등)", "인스타 'AI 정보' 라벨 켜기"], ["화자별 자막 색(흰/노랑)은 모든 2인극에 바로 적용 가능한 장치"])

RANK15 = page(
    15, "DbpJNIDzseF", "동생과 한강 투어 — 28.8초", "동생이랑 한강 투어했다 꾸이",
    [("조회수", "160만"), ("좋아요", "43,375"), ("댓글", "313"), ("업로드", "2026-08-05"), ("길이", "28.80초"),
     ("컷", "14"), ("fps", "30"), ("배경음악", "있음")],
    "유람선에서 갈매기가 새우깡 강탈 '내 새우깡!!!' → 선착장 '한강에서는 라면을 먹어야한대' → 편의점 라면 → 돗자리 라면 먹방 → 비둘기 습격 '짜증나…' → 사람들이 치킨 나눠줌 '제 이름은 김꾸이입니다~'.",
    "서울 관광 명소(한강 유람선·롯데타워·편의점 라면) 체크리스트 + 동물 습격 개그 2번(갈매기·비둘기).",
    [("0–5.5초", "갈매기 강탈 훅", "갈매기 클로즈업 → 과자 낚아채기 = 한강 유람선 실제 공감 밈."),
     ("6.5–13초", "한강 라면", "'한강에서는 라면을 먹어야한대' = 트렌드 공감."),
     ("13–21초", "먹방 + 비둘기", "라면 먹방 중 비둘기 떼 → '짜증나…'."),
     ("23–28.8초", "사람들의 친절", "옆 사람들이 치킨을 나눠 줌 → 자기소개 = 훈훈 엔딩.")],
    [s(1, 0.0, 2.0, "유람선 갑판", "MS", "고정", "갑판 난간, 뒤 승객들, 앞 새우과자 봉지", "과자 먹는 중 갈매기 접근", "없음", "갈매기", "하드컷",
       f"{CH} and {C2} (black-and-white) on the deck of a Han River cruise boat with a bag of shrimp crackers (fictional brand), passengers behind, sunny", "A seagull swoops in. Static camera.", K),
     s(2, 2.0, 3.5, "갈매기 CU", "CU", "고정", "갈매기 얼굴 가득", "부리를 크게 벌림", "없음", "끼룩", "하드컷", "close-up of a seagull opening its beak wide, city skyline behind", "It screams.", ["veo31"]),
     s(3, 3.5, 5.5, "강탈", "MS", "고정", "같은 갑판", "과자 봉지를 낚아챔", "내 새우깡!!!", "비명", "하드컷", "", "The seagull snatches the snack bag; they scream.", ["minimaxh3", "klingomni"], LABEL + " (새우깡)"),
     s(4, 5.5, 6.5, "떠나는 배", "WS", "고정", "강 위 유람선", "", "이리 내놔!", "", "하드컷", "", "Wide shot of the cruise boat on the river.", ["hailuo23"]),
     s(5, 6.5, 10.0, "선착장", "MS", "고정", "선착장, 뒤 유람선·타워", "걸어옴", "언니 나 너무 배고파 / 한강에서는 라면을 먹어야한대", "", "하드컷",
       f"{CH} and {C2} walking on a river pier with people leaving a cruise boat and a tall skyscraper behind", "They waddle forward chatting.", K),
     s(6, 10.0, 12.8, "편의점 라면", "MS/CU", "고정", "라면 진열대 → 즉석 라면 기계", "라면 고르기 → 끓이기", "향기로운 냄새~", "", "하드컷",
       "", "They pick a ramen pack and cook it at a convenience-store ramen machine.", K, LABEL + " (신라면)"),
     s(7, 12.8, 17.0, "돗자리 라면 먹방", "MS", "고정", "캐릭터 얼굴 패턴 돗자리, 한강 공원", "면 후루룩", "없음", "후루룩", "하드컷",
       f"{CH} and {C2} slurping ramen from paper bowls on a picnic mat printed with their own faces in a Han River park", "They slurp noodles.", K),
     s(8, 17.0, 21.3, "비둘기 습격", "WS/MS", "고정", "잔디 비둘기 떼 → 라면 뺏김", "비둘기가 다가와 라면을 먹음", "짜증나...", "", "디졸브",
       "", "Pigeons approach and peck at their ramen; they look annoyed.", ["klingomni", "minimaxh3"]),
     s(9, 21.3, 23.3, "강변 산책", "FS", "고정", "강변 길", "걸어감", "없음", "", "하드컷", "", "They walk along the riverside.", K),
     s(10, 23.3, 28.8, "치킨 나눔", "MS", "고정", "돗자리 위 캐릭터, 옆 사람들", "사람들이 치킨을 줌", "제 이름은 / 김꾸이입니다~ / 자, 여기~", "", "영상 끝",
       "", "Friendly people sitting nearby offer them fried chicken.", ["veo31", "klingomni"])],
    [ev(4.2, 5.3, "내 새우깡!!!", "My snack!!!"), ev(5.3, 6.5, "이리 내놔!", "Give it back!"), ev(6.5, 8.25, "언니 나 너무 배고파", "Sis, I'm so hungry"),
     ev(8.25, 10.0, "한강에서는 라면을 먹어야한대", "They say you have to eat ramen at the Han River"),
     ev(11.7, 12.8, "향기로운 냄새~", "Mmm, smells so good~"), ev(20.0, 21.3, "짜증나...", "So annoying..."),
     ev(23.25, 24.25, "제 이름은", "My name is"), ev(24.25, 26.0, "김꾸이입니다~", "Ggooii Kim~"), ev(26.25, 27.5, "자, 여기~", "Here you go~")],
    STD,
    {"summary": "밝은 BGM + 갈매기·후루룩 효과음.", "cues": [("0–28.8", "BGM", "")],
     "music_prompt": "Suno v5.5 — sunny city picnic pop, 112 BPM, acoustic guitar and whistles, 29 seconds, instrumental",
     "sfx_prompts": ["seagull squawk close up, 1 second"], "voice": "'꾸이' + 자막"},
    [("추천", "캐릭터 = Kling v3 Omni · 갈매기·비둘기 = MiniMax H3/Veo 3.1", "관광지 실제 배경은 이미지 단계에서", "약 10컷 ≈ 약 350~500")],
    [LABEL + " (새우깡·신라면)", "인스타 'AI 정보' 라벨 켜기"], ["도시 관광 시리즈(여의도·남산·홍대)"])

RANK16 = page(
    16, "DdTVlOUiOmo", "김미루(고양이)와 한정선 먹방 — 31.9초", "김꾸이랑 한정선 먹방 🍡 #김미루",
    [("조회수", "17.1만"), ("좋아요", "6,867"), ("댓글", "57"), ("업로드", "2026-09-15"), ("길이", "31.92초"),
     ("컷", "25"), ("fps", "24"), ("배경음악", "있음")],
    "다른 AI 캐릭터 계정 '김미루'(아기 고양이)와의 콜라보. 전화 약속 → 가게 앞 만남 '너 살 왜 이렇게 쪘냐?' → 디저트 쇼케이스 하트 눈 → 먹방 → 마지막 하나 쟁탈전 → 꾸이가 몰래 먹음 → 미루 분노 '복숭아 요거트 내 최애란 말이야!'.",
    "⚠️ 7위와 같은 브랜드(한정선) 협찬으로 보임. 콜라보 + 협찬 이중 구조. 끝에 '김미루' 로고 = 상대 계정 홍보.",
    [("0–6초", "분할 통화", "각자 침대에서 통화 → 미루 속마음 '(약속 취소됐으면 좋겠다…)' 괄호 자막 = 반전 속마음."),
     ("6–10.5초", "티격태격 만남", "'너 살 왜 이렇게 쪘냐?' '아니거든?!' = 친구 케미."),
     ("11–22초", "디저트 먹방", "하트 눈 이펙트 + 매크로 디저트 = 음식 광고."),
     ("22–31초", "쟁탈전", "눈 익스트림 클로즈업 대치 → 꾸이가 들고 도망 → 미루 불꽃 눈 분노."),
     ("31–31.9초", "콜라보 로고", "'김미루' 엔드카드 = 상호 홍보.")],
    [s(1, 0.0, 6.0, "분할 통화", "MCU 교차", "고정", "꾸이(분홍 침대) ↔ 미루(흰 침대)", "통화", "한 달 전 약속 잊지않았지? / 아... / 한정선 사줄테니까 나와! / (약속 취소됐으면 좋겠다...)", "", "하드컷",
       f"{CH} lying in a pink bed talking on a sparkly pink phone", "Cross-cut phone call with a sleepy baby kitten in a white bed.", K, "상대 캐릭터 = 다른 창작자 IP → 협의 필요"),
     s(2, 6.0, 10.5, "가게 앞 만남", "MS", "고정", "디저트 가게 앞, 고양이 캐릭터", "인사·티격태격", "미루야! / 야, 김꾸이 / 너 살 왜 이렇게 쪘냐? / 아니거든?!", "", "하드컷",
       "a cute anthropomorphic baby kitten in a grey knit top and jeans with a shoulder bag in front of a traditional dessert shop (fictional sign)", "They meet and bicker.", K, LABEL + " (한정선 간판)"),
     s(3, 10.5, 14.0, "쇼케이스 하트 눈", "CU", "고정", "쇼케이스·하트 눈 이펙트", "침 흘리며 감탄", "(와... 진짜 맛있겠다...)", "", "하드컷", "", "Heart-shaped sparkles appear in their eyes.", K),
     s(4, 14.0, 22.5, "먹방", "MS/CU", "고정", "포장 떡들, 매크로", "포장 풀고 먹기", "한정선 먹방 시작~! / 복숭아 요거트맛!♥", "", "하드컷", "", "They unwrap and eat peach-yogurt rice cakes.", K),
     s(5, 22.5, 24.5, "눈 대치", "ECU", "고정", "눈 익스트림 클로즈업 교차", "마지막 하나를 노려봄", "없음", "긴장음", "하드컷", "", "Extreme close-ups of their eyes glaring (western standoff).", K),
     s(6, 24.5, 28.0, "몰래 먹기", "MS", "고정", "구석", "들고 도망쳐 먹음", "야! 김꾸이!!!", "", "하드컷", "", "It grabs the last one and eats it in the corner.", K),
     s(7, 28.0, 30.8, "불꽃 눈 분노", "CU", "고정", "고양이 얼굴, 눈에 불꽃", "분노", "복숭아 요거트 내 최애란 말이야!", "", "하드컷", "", "The kitten's eyes burst into flames.", ["seedance25", "minimaxh3"]),
     s(8, 30.8, 31.92, "콜라보 로고", "그래픽", "고정", "검정 배경 로고", "", "김미루 (로고)", "", "영상 끝", "", "", [])],
    [ev(0.0, 1.5, "한 달 전 약속 잊지않았지?", "Remember our plans from last month?"), ev(1.6, 2.6, "아...", "Uh..."),
     ev(3.0, 3.7, "한정선 사줄테니까 나와!", "Come out! I'll treat you to Hanjungsun!"),
     ev(3.75, 6.0, "(약속 취소됐으면 좋겠다...)", "(I wish the plan got cancelled...)"), ev(6.7, 7.3, "미루야!", "Miru!"),
     ev(7.7, 8.3, "야, 김꾸이", "Hey, Ggooii Kim"), ev(8.7, 9.75, "너 살 왜 이렇게 쪘냐?", "How'd you gain so much weight?"),
     ev(9.75, 10.5, "아니거든?!", "I did not!"), ev(11.0, 12.8, "(와... 진짜 맛있겠다...)", "(Wow... that looks so good...)"),
     ev(14.25, 15.0, "한정선 먹방 시작~!", "Hanjungsun mukbang start~!"), ev(16.25, 20.25, "복숭아 요거트맛!♥", "peach yogurt flavor! ♥"),
     ev(25.2, 26.0, "야! 김꾸이!!!", "Hey! Ggooii Kim!!!"), ev(28.0, 29.3, "복숭아 요거트 내 최애란 말이야!", "Peach yogurt is my favorite!")],
    {**STD, "kr_y": 0.656},
    {"summary": "귀여운 BGM + 대결 장면 긴장음.", "cues": [("0–31.9", "BGM", "")],
     "music_prompt": "Suno v5.5 — cute playful K-pop cafe BGM, 105 BPM, with a spaghetti-western standoff twang at 22 seconds, 32 seconds, instrumental",
     "sfx_prompts": ["western standoff whistle and tension sting, 2 seconds"], "voice": "두 캐릭터 + 자막"},
    [("추천", "두 캐릭터 = Kling v3 Omni(레퍼런스 2장) · 불꽃·하트 눈 = 편집 이펙트 또는 Seedance", "콜라보는 상대 창작자와 캐릭터 시트 공유가 필수", "약 8비트 ≈ 약 300~450")],
    ["⚠️ 다른 창작자 캐릭터(김미루) 무단 사용 금지 — 콜라보 합의", LABEL + " (한정선, 협찬 표기 확인)", "인스타 'AI 정보' 라벨 켜기"],
    ["AI 캐릭터 계정끼리 콜라보 = 서로의 팔로워 교환(성장 레버)"])

RANK17 = page(
    17, "Db5Nb5px2d_", "햄스터와 친구 된 썰 — 33.5초", "꾸이랑 친구된 썰 👯 how we became bff",
    [("조회수", "75.7만"), ("좋아요", "57,509"), ("댓글", "252"), ("업로드", "2026-08-11"), ("길이", "33.50초"),
     ("컷", "20"), ("fps", "30"), ("배경음악", "있음")],
    "북촌 한옥길에서 꾸이와 큰 눈 햄스터가 길을 막고 시비 '니 뭔데 비켜라' → 분할 화면 대치 → 햄스터가 꾸이 등에 올라탐 '당장 내려오지 못해!!??' → '우리 치킨 ㄱㄱ? 내가 쏨' → '아싸 치킨!!!' 절친 엔딩.",
    "입만 보이는 익스트림 클로즈업 대사 + 분할 화면(스플릿 스크린) 대치가 핵심. 자막은 한국어 반말 + 영어 슬랭 번역('Tiny ass thing acting tough').",
    [("0–1.5초", "길막 훅", "좁은 한옥 골목에서 두 동물이 마주침."),
     ("1.5–12초", "입 클로즈업 말싸움", "입술만 보이는 대사 컷 교차 = 밈 '말싸움' 포맷."),
     ("12.5–15초", "분할 화면 대치", "좌우 스플릿 스크린 = 서부극 대치 패러디."),
     ("15–24초", "등 위에 올라탐", "작은 햄스터가 올라타 → '내려오지 못해!!' → '치킨 ㄱㄱ? 내가 쏨'."),
     ("24–33.5초", "절친 엔딩", "'아싸 치킨!!!' '가보자고!!!' 함께 한옥길을 걸어감 → 뒷모습 롱샷.")],
    [s(1, 0.0, 1.5, "골목 마주침", "WS", "고정", "돌담 앞 좌우로 마주 선 둘", "마주침", "없음", "", "하드컷",
       f"{CH} and a tiny tan hamster with huge glossy black eyes face each other on a stone path in a Korean hanok alley with a grey stone wall", "They stop face to face. Static camera.", K),
     s(2, 1.5, 12.5, "입 클로즈업 말싸움", "ECU 교차", "고정", "입·코만 화면 가득(교차)", "번갈아 말함", "니 뭔데 비켜라 / 왜 나한테 그래? 니가 비켜가 / 좋은 말로 할때 얼른 비켜라 / 쪼끄만한게 까불고 있어 진짜 주글래?",
       "대사", "하드컷", "extreme close-up of [CHARACTER]'s human-like lips and snout", "Alternating extreme close-ups of their mouths arguing.", K),
     s(3, 12.5, 15.0, "분할 화면 대치", "스플릿", "고정", "화면 좌우 2분할", "노려봄", "없음", "긴장음", "하드컷", "", "Split screen: both glare at each other.", K, "편집에서 2분할 레이아웃"),
     s(4, 15.0, 19.0, "달려와 올라탐", "FS/CU", "고정", "한옥길 중앙", "햄스터가 등에 올라탐", "근데 얘 좀 짜증나게 귀엽네;;", "", "하드컷", "", "The hamster climbs onto its back.", K),
     s(5, 19.0, 24.0, "'내려오지 못해!!'", "ECU/MS", "고정", "입 클로즈업 ↔ 등 위 햄스터", "화냄 → 치킨 제안", "너!!! 당장 내려오지 못해!!?? / 안돼 우리 치킨 ㄱㄱ? 내가 쏨", "대사", "하드컷", "", "Argument, then an offer of chicken.", K),
     s(6, 24.0, 31.0, "'아싸 치킨!'", "ECU", "고정", "활짝 웃는 입", "환호", "아싸 치킨 !!!!!!!!!! / 가보자고!!!!!!!!", "환호", "하드컷", "", "Both cheer with wide grins.", K),
     s(7, 31.0, 33.5, "함께 걷는 뒷모습", "EWS", "고정", "한옥길 소실점 중앙에 작게", "나란히 걸어감", "없음", "", "영상 끝",
       "extreme wide shot of a hanok village alley with a long stone path, two tiny animals walking away together", "They walk away side by side.", ["seedance25"])],
    [ev(1.5, 2.6, "니 뭔데 비켜라", "move get out the way"), ev(2.75, 3.8, "왜 나한테 그래? 니가 비켜가", "Why me? You move"),
     ev(4.25, 5.8, "좋은 말로 할때 얼른 비켜라", "Move while I'm still asking nicely"),
     ev(7.75, 9.5, "쪼끄만한게 까불고 있어 진짜 주글래?", "Tiny ass thing acting tough. You wanna die?"),
     ev(18.75, 19.5, "근데 얘 좀 짜증나게 귀엽네;;", "Okay but... why is this thing annoyingly cute?"),
     ev(19.5, 20.8, "너!!! 당장 내려오지 못해!!??", "Get down. Right now!!!!"),
     ev(21.0, 22.0, "안돼 우리 치킨 ㄱㄱ? 내가 쏨", "Nah. r u down for chicken? It's on me"),
     ev(25.5, 26.5, "아싸 치킨 !!!!!!!!!!", "LET'S GOOO, CHICKEN!"), ev(29.5, 30.8, "가보자고!!!!!!!!", "LET'S GOOO!!!!!!")],
    {**STD, "kr_y": 0.718, "kr_size": 46, "en_size": 30, "en_dy": 0.03},
    {"summary": "BGM + 대사. 대치 구간 긴장음, 엔딩 신나는 곡.", "cues": [("0–33.5", "BGM", "")],
     "music_prompt": "Suno v5.5 — tense comedic standoff beat turning into a hype celebration drop at 25 seconds, 100 to 128 BPM, 34 seconds, instrumental",
     "sfx_prompts": ["dramatic standoff wind and bell, 2 seconds"], "voice": "두 캐릭터 + 자막"},
    [("추천", "캐릭터 둘 = Kling v3 Omni · 입 클로즈업 = 이미지 1장 + 립 움직임 i2v", "스플릿 화면은 편집(HyperFrames 2분할 레시피)", "약 7비트 ≈ 약 250~400")],
    ["큰 눈 햄스터는 유명 밈 캐릭터와 닮을 수 있음 — 독자 디자인으로", "인스타 'AI 정보' 라벨 켜기"],
    ["'OO랑 친구된 썰' 시리즈: 매번 다른 동물 친구 추가 → 세계관 확장"])

PAGES_11_17 = [RANK11, RANK12, RANK13, RANK14, RANK15, RANK16, RANK17]
