"""3위 — 버거집 알바 (DbAXwGtCURh): 22.4초, 13샷."""

C = "[CHARACTER] wearing a black baseball cap and a black polo uniform with a fictional burger-shop logo"
KITCHEN = "stainless-steel fast-food kitchen, warm overhead lights, menu screens in the background"


def s(i, t0, t1, name, size, move, comp, action, text, sound, out, img, vid, models, note=""):
    return {"id": f"S{i:02d}", "t0": t0, "t1": t1, "name": name, "size": size, "angle": "아이레벨(카운터 높이)",
            "lens": "", "move": move, "comp": comp, "action": action, "bg": "", "light": "", "text": text,
            "sound": sound, "out": out, "img": img, "vid": vid, "models": models, "note": note}


RANK3 = {
    "rank": 3, "id": "DbAXwGtCURh", "file": "rank3.html",
    "title": "버거집 알바 — 22.4초 · 13샷",
    "caption": "꾸이의 맥도날드 알바 도전기",
    "url": "https://www.instagram.com/reel/DbAXwGtCURh/",
    "stats": [("조회수", "600만"), ("좋아요", "156,473"), ("댓글", "1,798"), ("업로드", "2026-07-20"),
              ("길이", "22.40초"), ("샷", "13 (전환 12)"), ("평균 샷 길이", "1.72초"), ("배경음악", "있음 ('꾸이' 징글)")],
    "one_liner": ("신나게 버거·감튀·콜라를 준비(점점 빨라지는 몽타주) → 거대한 보디빌더 손님이 작은 봉투를 보고 "
                  "'간에 기별도 안 가겠네…' → 혼자 바닥에 앉아 울면서 먹는데 '그 와중에 맛있어…'. 22초 3막 코미디."),
    "structure_note": ("카메라는 모든 샷에서 고정(락오프) — 움직임은 캐릭터만. 마지막 샷만 20.97초에 4프레임 크래시 줌(펀치 인) 후 "
                       "천천히 푸시인해 눈물 익스트림 클로즈업으로 끝남(자동 감지가 놓쳐 프레임 확인으로 13샷으로 보정)."),
    "viral": [
        ("0.0–1.5초", "유명 브랜드 유니폼 + 노래", "작은 캐릭터가 누구나 아는 패스트푸드 유니폼을 입고 흥얼거리며 버거를 만듦 → 설정이 1초 만에 이해됨."),
        ("6.0–11.6초", "점점 빨라지는 몽타주", "샷 길이 6.0 → 1.07 → 1.03 → 0.67 → 0.40 → 0.83초. 리듬이 빨라지며 '일 잘하는 중' 에너지 상승."),
        ("7.1–9.2초", "음식 광고 인서트", "튀김 기름·감튀 쏟아지는 클로즈업(0.4초 초단 컷 포함) = 만족감 ASMR."),
        ("8.1–10.0초", "스케일 개그 ①", "캐릭터가 담는 감튀 상자가 손톱만 함 — 뒤에 나올 반전의 복선."),
        ("11.6–16.3초", "반전: 거대 손님", "근육질 보디빌더 vs 작은 봉투. '뭐야 이게…?' → '간에 기별도 안 가겠네…' = 한국어 관용구 공감 개그."),
        ("16.3–19.7초", "3초 정적", "손님이 나가는 뒷모습 + 남겨진 봉투. 자막 없는 침묵이 슬픔을 만듦."),
        ("19.7–22.4초", "이중 펀치라인", "'열심히 만들었는데…'(슬픔) → 크래시 줌 → '그 와중에 맛있어…'(자기 위로 개그). 댓글 유발."),
        ("전체", "3개 언어 자막 + 꾸이 노래", "캐릭터는 '꾸이' 노래만, 뜻은 한·영·일 자막. 사람 배우만 한국어 대사."),
    ],
    "cast": [
        ("[CHARACTER] (꾸이 역)", "검정 캡 모자 + 검정 폴로 유니폼(가상 로고)"),
        ("[CUSTOMER]", "근육질 한국인 보디빌더, 검정 민소매. 원본은 실사 사람 배우(AI)"),
        ("[COWORKER]", "얼굴이 안 나오는 사람 직원 상반신(검정 앞치마)"),
    ],
    "shots": [
        s(1, 0.0, 6.0, "버거 만들기", "MS", "고정",
          "캐릭터 중앙, 재료 트레이가 하단 1/3 가로, 뒤에 메뉴 화면", "치즈 올리기 → 머스터드 지그재그 → 포장 → 들어 보이기",
          "정성을 담아서~♬ / 햄버거를 만들자~♬ / 버거야 맛있어져라~ / 완성!", "'꾸이 꾸이' 흥얼 노래 + BGM", "하드컷",
          f"{C} behind a burger prep station with trays of pickles, diced onion, shredded lettuce, cheese slices and buns, squeeze bottles of mustard and ketchup, a burger on wax paper in front; {KITCHEN}; eye level, 35mm, character centered",
          "Working happily: it places a cheese slice on the patty, squeezes mustard in a zigzag, wraps the burger in paper and holds it up proudly, humming 'kkui kkui kkui kkui'. Locked-off static camera.",
          ["klingomni", "seedance25"], "손으로 소품 다루기 → Kling v3 Omni. 6초 1컷"),
        s(2, 6.0, 7.067, "튀김기에 투하", "WS", "고정",
          "캐릭터 좌측 작게, 우측에 사람 직원 상반신(얼굴 X), 전경 좌측 감튀 상자", "튀김 바스켓을 기름에 내림",
          "감튀 투하!", "기름 치익", "하드컷",
          f"wide shot: {C}, tiny next to a human coworker's torso in a black apron (face out of frame), lowering a fry basket into a deep fryer; red fry cartons in the left foreground, salt shaker, stainless steel",
          "It lowers the basket into the hot oil; bubbles start. Static camera.", ["klingomni", "seedance25"]),
        s(3, 7.067, 8.1, "지글지글 인서트", "CU 인서트", "고정",
          "바스켓이 화면 중앙 사선, 기름 거품", "감튀가 기름 속에서 튀겨짐",
          "향기~ (7.25초부터)", "튀김 ASMR", "디졸브 0.1초",
          "close-up of golden fries in a wire fryer basket submerged in vigorously bubbling oil, steam, food commercial look",
          "Oil bubbles vigorously around the fries, satisfying sizzle, macro. Static camera.", ["minimaxh3", "veo31", "hailuo23"]),
        s(4, 8.1, 8.767, "손톱만 한 감튀 상자", "MS", "고정",
          "캐릭터 중앙, 작은 상자가 하단 중앙", "망 국자로 감튀를 초소형 상자에 담음(무표정)",
          "향기~", "", "디졸브 0.067초",
          f"medium shot: {C} behind the counter scooping fries with a mesh strainer into a comically tiny red fry carton, deadpan",
          "It pours fries into the tiny carton. Static camera.", ["klingomni", "seedance25"], "스케일 개그의 복선"),
        s(5, 8.767, 9.167, "감튀 쏟아지는 광고 컷 (0.4초)", "제품 CU", "고정",
          "빨간 상자가 화면 중앙 하단, 위에서 감튀가 떨어짐", "감튀가 큰 상자에 쏟아짐",
          "없음", "바삭 떨어지는 소리", "하드컷",
          "product shot: golden fries tumbling into a large red fry carton (fictional logo) on a stainless counter, studio lighting",
          "Fries tumble into the carton in slight slow motion. Static camera. (Generate 4s, use the best 0.4s.)",
          ["minimaxh3", "hailuo23"], "0.4초만 쓰므로 싼 모델로"),
        s(6, 9.167, 10.0, "'감튀 준비완료!'", "MS", "고정",
          "캐릭터 중앙, 망 국자·작은 상자", "뿌듯한 얼굴", "감튀 준비완료!", "", "하드컷",
          f"medium shot: {C} holding a mesh strainer next to a tiny full fry carton, proud smile",
          "It smiles proudly and nods. Static camera.", ["klingomni", "seedance25"]),
        s(7, 10.0, 11.567, "콜라 따르기", "MS", "고정",
          "음료 디스펜서가 상단 가로, 캐릭터 좌중앙, 컵이 중앙", "진지하게 컵에 콜라를 받음",
          "준비 끝! (10.95초부터)", "탄산 따르는 소리", "디졸브 0.1초",
          f"medium shot: {C} standing on a steel counter at a soda fountain with fictional drink labels, holding a paper cup under a nozzle while cola pours, ice dispenser",
          "Cola fills the cup with fizz while it watches seriously. Static camera.", ["klingomni", "seedance25"],
          "⚠️ 실제 음료 브랜드 라벨 금지"),
        s(8, 11.567, 13.367, "거대 손님 등장", "WS 오버숄더", "고정",
          "우측 전경에 거대한 등·팔, 좌중앙 카운터 위 캐릭터, 상단 메뉴판", "캐릭터가 작은 봉투를 두 손으로 건넴",
          "주문 나왔습니다~!", "'꾸이!'", "하드컷",
          f"wide over-the-shoulder shot from behind a huge muscular bodybuilder in a black tank top at a fast-food counter with menu boards above; {C} on the counter hands him a small paper bag with both paws; cash register beside",
          "It lifts the small bag toward the man and squeaks proudly; the man takes it with two fingers. Static camera.",
          ["veo31", "klingomni"], "사람 실사 → Veo 3.1"),
        s(9, 13.367, 14.067, "'뭐야 이게…?'", "MS", "고정",
          "손님 가슴 위 중앙, 작은 봉투가 중앙 하단", "작은 봉투를 들여다보며 찡그림",
          "뭐야 이게...?", "굵은 남성 한국어 대사", "하드컷",
          "medium shot of a very muscular Korean bodybuilder in a black tank top holding a tiny paper bag with a puzzled frown, fast-food restaurant interior",
          "He stares at the tiny bag and mutters in Korean '뭐야 이게...?' in a deep voice. Static camera.",
          ["veo31", "seedance25"], "한국어 립싱크 → Veo 3.1 (4초 생성 후 0.7초 사용)"),
        s(10, 14.067, 16.267, "'간에 기별도 안 가겠네…'", "MS-WS", "고정",
          "손님 우측, 캐릭터 좌측 작게", "봉투를 들고 돌아서며 투덜",
          "간에 기별도 안가겠네...", "한국어 대사(한숨)", "디졸브 0.067초",
          f"medium-wide shot: the bodybuilder turns away from the counter holding the tiny bag; {C} small on the counter at left watching",
          "He sighs '간에 기별도 안 가겠네...' and walks off. Static camera.", ["veo31", "seedance25"]),
        s(11, 16.267, 18.367, "떠나는 뒷모습", "WS 로우앵글", "고정",
          "좌측 전경 캐릭터 옆·뒷모습, 중앙 카운터 위 남겨진 봉투, 멀리 유리문", "손님이 문으로 나감, 캐릭터는 말없이 봄",
          "없음 (정적)", "BGM만", "하드컷",
          f"low-angle wide shot from counter level behind {C}, the rejected small paper bag lying on the counter, the bodybuilder walking out through glass doors in the distance, daylight outside",
          "The man exits through the doors; it watches silently. Static camera.", ["klingomni", "veo31"]),
        s(12, 18.367, 20.967, "바닥에서 울며 먹기", "MS", "고정",
          "캐릭터 중앙 하단(바닥에 앉음), 스테인리스 벽 우측, 바닥 부스러기", "작은 버거를 조금씩 먹으며 눈물",
          "열심히 만들었는데... (19.7초부터)", "훌쩍임 + BGM", "크래시 줌 0.133초(4프레임)",
          f"medium shot: {C} sitting on the kitchen tile floor against a stainless-steel wall, eating a tiny burger with both paws, tears streaming down its cheeks, crumbs on the floor, cool back-of-house lighting",
          "It takes small bites while crying silently, tears rolling. Static camera.", ["klingomni", "seedance25"]),
        s(13, 20.967, 22.4, "눈물 익스트림 CU", "CU → ECU", "슬로 푸시인",
          "눈·볼·눈물 줄기가 화면 가득, 모자 챙이 상단", "떨리는 입술로 씹으며 눈물",
          "그 와중에 맛있어...", "", "영상 끝",
          "extreme close-up of the face of [CHARACTER] under a black cap brim: glossy tear streaks, human-like teary eyes, a burger bite near the lips",
          "Slow push-in while it chews with a trembling lip and a tear rolls down.", ["klingomni", "seedance25"],
          "EDL: 이 컷에 push 0.10 적용(10% 확대)"),
    ],
    "gen_plans": [
        ("추천 조합", "캐릭터 컷 8개 = Kling v3 Omni · 사람 대사 컷 3개(S08~S10) = Veo 3.1 · 음식 인서트 2개(S03·S05) = MiniMax H3/Hailuo 2.3",
         "모든 AI 클립 오디오는 끄거나 낮추고(clip_gain), 손님 대사만 살림 → 음악(Suno)으로 전체를 덮고 대사 구간만 덕킹(EDL에 설정됨).",
         "키프레임 13장 × 9 + 영상 13개 × 20~48 + 음악 18 ≈ 약 450~700 × 재시도"),
    ],
    "transitions": [
        {"t": "8.10 · 11.57초", "type": "짧은 디졸브", "frames": "3프레임(0.1초)", "how": "AI 클립 이음새를 부드럽게",
         "ffmpeg": "xfade=transition=fade:duration=0.1", "capcut": "디졸브 0.1초", "pro": "Cross Dissolve 3f"},
        {"t": "8.77 · 16.27초", "type": "초단 디졸브", "frames": "2프레임(0.067초)", "how": "거의 컷처럼 보이는 소프트 컷",
         "ffmpeg": "xfade=transition=fade:duration=0.067", "capcut": "디졸브 최소값", "pro": "Cross Dissolve 2f"},
        {"t": "20.97초", "type": "크래시 줌(펀치 인)", "frames": "4프레임(0.133초)", "how": "MS에서 CU로 확 당겨진 뒤 천천히 푸시인",
         "ffmpeg": "xfade=transition=zoomin:duration=0.133 + 다음 샷 push 0.10", "capcut": "줌 인 전환 + 키프레임 확대",
         "pro": "AE: 스케일 100→160% (Easy Ease 없음) 4f"},
        {"t": "나머지 7곳", "type": "하드 컷", "frames": "0", "how": "6.00·7.07·9.17·10.00·13.37·14.07·18.37초",
         "ffmpeg": "하드컷(concat)", "capcut": "없음", "pro": "Cut"},
    ],
    "audio": {
        "summary": ("처음부터 끝까지 음악이 깔림(무음 구간 0). 스펙트럼상 템포 약 72 BPM(=144 하프타임 느낌 추정), "
                    "캐릭터가 '꾸이 꾸이'로 멜로디를 부르는 징글 + 손님 한국어 대사(13.4~17초). 11개 컷 중 7개가 소리 시작점과 일치. "
                    "-14.0 LUFS / LRA 5.6 / 트루피크 -2.1 dBFS(안전). 라이선스 음원 표기 없음 → 자체 제작 음원 추정."),
        "cues": [
            ("0.0–13.0", "'꾸이 꾸이 꾸이' 노래 + 밝은 징글", "♬ 자막과 함께"),
            ("13.4–14.4", "손님: '뭐야 이게'", "음악 덕킹"),
            ("14.4–17.0", "손님: '간에 기별도 안 가겠네'", "음악 덕킹"),
            ("16.3–19.7", "정적 (음악만, 자막 없음)", "슬픔 빌드업"),
            ("19.7–22.4", "'꾸이…' 훌쩍 + 음악 계속", "엔딩"),
        ],
        "music_prompt": ("Suno v5.5 — cute upbeat kids-show jingle, 144 BPM half-time feel, ukulele, glockenspiel, handclaps, "
                         "soft kick, bright major key, squeaky chipmunk-like vocal singing only the nonsense syllables "
                         "'kkui kkui kkui kkui'; at 13 seconds the band drops out except a soft pad; from 18 seconds a slow sad "
                         "piano and music-box outro; about 23 seconds, no other lyrics  (※ 원곡 확인 불가 — 스펙트럼 기반 재현 제안)"),
        "sfx_prompts": ["deep fryer basket dropped into hot oil, loud sizzle, 1 second",
                        "soda fountain pouring cola into a paper cup with ice, fizz, 1.5 seconds"],
        "voice": ("캐릭터 = 음악 속 '꾸이' 노래로 대신(대사 없음). 손님 = Veo 3.1 네이티브 한국어 대사, 또는 ElevenLabs v3 "
                  "굵은 남성 목소리 TTS를 클립에 얹기."),
    },
    "edl": ["edl_rank3_burger.json"],
    "hf": ["hyperframes/rank3_burger/index.html"],
    "legal": [
        "⚠️ 맥도날드 로고·유니폼·포장, 코카콜라·스프라이트·닥터페퍼 라벨 = 등록상표. 수익 계정이면 가상 브랜드(예: '꾸이버거')로 교체 필수",
        "⚠️ 실존 인물처럼 보이는 사람 배우는 AI 생성 인물로, 특정 유명인을 닮게 만들지 않기",
        "인스타 'AI 정보' 라벨 켜기",
    ],
    "enhance": [
        "몽타주 컷 길이를 비트에 맞추면(원본은 11컷 중 7컷만 일치) 리듬감이 더 좋아짐 — HyperFrames `hyperframes beats`로 비트 시각 추출 가능",
        "알바 시리즈화: 편의점·카페·세차장 등 장소만 바꿔 같은 3막(신남→반전 손님→눈물+펀치라인) 반복",
    ],
}
