"""4~10위 분석 콘텐츠."""

CH = "[CHARACTER]"


def s(i, t0, t1, name, size, move, comp, action, text, sound, out, img, vid, models, note="", tr=None):
    d = {"id": f"S{i:02d}", "t0": t0, "t1": t1, "name": name, "size": size, "angle": "아이레벨", "lens": "",
         "move": move, "comp": comp, "action": action, "bg": "", "light": "", "text": text, "sound": sound,
         "out": out, "img": img, "vid": vid, "models": models, "note": note}
    if tr:
        d["tr"] = tr
    return d


def ev(t0, t1, kr, en, jp=""):
    return {"t0": t0, "t1": t1, "kr": kr, "en": en, "jp": jp}


def page(rank, vid, title, caption, stats, one, note, viral, shots, subs, style, audio, plans, legal, enhance, cast=None):
    return {"rank": rank, "id": vid, "file": f"rank{rank}.html", "title": title, "caption": caption,
            "url": f"https://www.instagram.com/reel/{vid}/", "stats": stats, "one_liner": one,
            "structure_note": note, "viral": viral, "shots": shots, "subs": subs, "subs_style": style,
            "audio": audio, "gen_plans": plans, "transitions": [], "legal": legal, "enhance": enhance,
            "cast": cast or [], "edl": [f"edl_rank{rank}.json"], "hf": [f"hyperframes/rank{rank}/index.html"]}


PINK_WALL = "pastel pink wallpaper with a repeating pattern of small guinea-pig faces"
YELLOW_WALL = "butter-yellow wallpaper with a repeating pattern of small guinea-pig figures"
LABEL = "⚠️ 원본에 실제 브랜드명이 보임 — 재현 시 가상 브랜드로"

RANK4 = page(
    4, "DcvaFq6ianJ", "마라탕 먹방 — 26.7초 원테이크", "마라탕 먹방이다 꾸이",
    [("조회수", "78.8만"), ("좋아요", "49,125"), ("댓글", "258"), ("업로드", "2026-09-01"), ("길이", "26.71초"),
     ("컷", "0 (고정 카메라 원테이크)"), ("fps", "24"), ("배경음악", "없음 (먹는 소리 ASMR)")],
    "고정 카메라 앞에서 마라탕을 국자·젓가락으로 먹는 26초 먹방. 컷 0, 카메라는 마지막에만 천천히 다가감. 자막은 처음 3초 두 줄뿐.",
    "편집이 거의 없는 'ASMR 먹방' 포맷. 재미는 사람처럼 먹는 기니피그의 동작(국자 후루룩, 면치기, 두부 한입)과 입가에 묻은 빨간 국물에서 나옵니다.",
    [("0.0–2.9초", "메뉴 소개 자막", "‘춘리마라탕 먹방이다 꾸이’ + 맵기 단계. 음식 이름·맵기 = 먹방 시청자가 제일 궁금한 정보를 첫 3초에."),
     ("2.9–17.5초", "사람 같은 먹기 동작", "국자로 떠서 후후 → 어묵볼 → 젓가락 면치기. '동물이 사람처럼 먹는다'가 핵심 훅."),
     ("17.5–21.5초", "두부 한입 + 국물 묻은 입", "빨간 국물이 입가에 묻는 디테일 = 공감·귀여움."),
     ("21.5–26.7초", "슬로 푸시인 엔딩", "카메라가 천천히 다가가며 무표정 씹기로 끝. 반복 재생 유도."),
     ("전체", "배경 패턴 벽지", "기니피그 얼굴 패턴 분홍 벽지 = 채널 시그니처 세트(8위와 같은 방식)."),],
    [s(1, 0.0, 2.9, "메뉴 소개", "MCU", "고정", "캐릭터 상반신 중앙, 마라탕 그릇이 하단 절반, 자막이 화면 중앙(y 46%)",
       "그릇 앞에 앉아 카메라 응시", "춘리마라탕 먹방이다 꾸이 / 매운맛 2단계 마라맛 3단계로 ㄱ", "'꾸이' 흥얼", "연속",
       f"{CH} sitting behind a black takeout bowl of mala tang (fried tofu, fish balls, sausage slices, greens, red chili broth) on a white table, {PINK_WALL}, medium close-up, eye level, 50mm, character centered, bowl fills the lower half",
       "It looks into the lens and hums 'kkui kkui'. Locked-off static camera.", ["seedance25", "klingomni"]),
     s(2, 2.9, 10.5, "국자로 떠먹기", "MCU", "고정", "같은 구도", "국자로 국물·어묵볼을 떠서 먹음", "없음",
       "후루룩·국자 소리", "연속", "", "It scoops broth and a fish ball with a steel ladle, blows on it and eats with human-like manners. Static camera.",
       ["klingomni", "seedance25"], "손으로 도구 쓰기 → Kling v3 Omni"),
     s(3, 10.5, 17.5, "면치기", "MCU", "고정", "같은 구도", "젓가락으로 넓은 면을 들어 올려 후루룩", "없음", "면 흡입 ASMR", "연속",
       "", "It lifts wide glass noodles high with wooden chopsticks and slurps them. Static camera.", ["klingomni", "seedance25"]),
     s(4, 17.5, 21.5, "두부 한입", "MCU", "고정", "같은 구도", "두부를 물고 입가에 빨간 국물", "없음", "씹는 소리", "연속",
       "", "It bites a piece of fried tofu; red broth drips at the corners of its lips. Static camera.", ["klingomni", "seedance25"]),
     s(5, 21.5, 26.71, "슬로 푸시인 엔딩", "MCU→CU", "슬로 푸시인", "얼굴이 점점 커짐, 그릇은 하단", "무표정으로 씹음", "없음",
       "씹는 소리", "영상 끝", "", "Slow push-in while it chews with a deadpan face, red broth on its lips.", ["seedance25", "klingomni"])],
    [ev(0.25, 1.05, "춘리마라탕 먹방이다 꾸이", "Today's mukbang is Chunri Malatang~"),
     ev(1.15, 2.9, "매운맛 2단계 마라맛 3단계로 ㄱ", "Let's go with spice level 2 and mala level 3!")],
    {"kr_size": 58, "en_size": 34, "kr_y": 0.46, "en_dy": 0.039, "jp_dy": 0.07, "jp_size": 30, "outline": 2.4, "shadow": 1.8},
    {"summary": "배경음악 없음. '꾸이' 흥얼 + 국자·면·씹는 ASMR. -15.7 LUFS / LRA 8.6 / 트루피크 +1.0 dBFS(넘침 → -1 dBTP 리미터 필수). Whisper가 뒷부분에서 '시청해 주셔서 감사합니다'를 들었다고 하지만 이는 무음·소음 구간의 전형적인 오인식이라 제외.",
     "cues": [("0.0–2.9", "'꾸이 꾸이' 흥얼", ""), ("2.9–17.5", "국자·후루룩·면 흡입", "ASMR"), ("17.5–26.7", "씹는 소리", "")],
     "music_prompt": "", "sfx_prompts": ["close-mic ASMR of slurping spicy noodle soup with a steel ladle, 8 seconds"],
     "voice": "영상 모델 오디오 켬 + 'ASMR eating sounds, tiny squeaky hum kkui kkui' 프롬프트."},
    [("추천 조합", "한 번에 12~15초 × 2클립(Seedance 2.5, 같은 첫 프레임) → 이어 붙이기. 또는 Kling v3 Omni 10초 × 3",
      "고정 카메라라 컷 이음새가 잘 안 보임. 마지막 5초는 push 0.12 적용(EDL).", "Seedance 2.5 720p 15초 ×2 ≈ 할인 약 360")],
    ["⚠️ '춘리마라탕'은 실제 가게명으로 보임(협찬/PPL 가능성) — 재현 시 가상 가게명", "인스타 'AI 정보' 라벨 켜기"],
    ["자막을 3초 이후에도 1~2줄(맵기 반응 '헉 매워')을 넣으면 체류시간 개선 여지", "음식만 바꿔 시리즈화: 마라탕→떡볶이→짜장면"])

RANK5 = page(
    5, "DcLbxpuima4", "꾸이티걸 댄스 — 19.3초", "꾸이티걸 #capcutseedance25",
    [("조회수", "100만"), ("좋아요", "48,838"), ("댓글", "324"), ("업로드", "2026-08-18"), ("길이", "19.27초"),
     ("컷", "1 (댄스 원테이크 + 로고 엔드카드)"), ("fps", "30"), ("배경음악", "있음 (댄스곡)")],
    "걸그룹 콘셉트 의상(분홍 'BABY GIRL 02' 티 + 민트 치마)의 캐릭터가 17초 동안 춤추고, 흰 화면 '꾸이티걸' 로고로 끝. 자막 0줄.",
    "캡션의 #capcutseedance25 · 'CapCut AI 기능으로 제작' 표기 → CapCut의 AI 댄스 템플릿(Seedance 2.5)으로 만든 영상. 카메라는 얼굴 클로즈업에서 풀샷으로 빠진 뒤 고정.",
    [("0–2초", "얼굴 클로즈업 → 풀백", "사람 눈·입술의 무표정 얼굴로 시작해 전신 의상이 드러남 = 반전 훅."),
     ("2–17초", "K팝 걸그룹 안무", "귀여운 동물이 진지하게 걸그룹 춤 = 밈 공식. 트렌드 댄스를 따라 할수록 검색 유입."),
     ("17–19.3초", "브랜드 엔드카드", "'꾸이티걸' 로고 = 캐릭터 IP화(굿즈·시리즈명)."),
     ("전체", "무자막·음악 100%", "언어 장벽 0 → 해외 노출 유리.")],
    [s(1, 0.0, 17.57, "댄스 원테이크", "ECU→FS", "0~2.5초 풀백 후 고정",
       "처음엔 얼굴이 화면 가득 → 전신 중앙, 분홍·하늘 그라데이션 배경 + 바닥 네온 라인",
       "걸그룹 안무(팔 흔들기·하트·골반 흔들기), 무표정 립싱크", "없음", "댄스곡", "휩/블러로 흰 화면",
       f"{CH} wearing a pink striped oversized T-shirt printed 'BABY GIRL 02', a mint pleated mini skirt with a silver belt and pearl bracelets, standing on a glossy floor in front of a pink-to-sky-blue gradient studio wall with a thin neon line at the horizon, full body, eye level, 35mm",
       "Starts as an extreme close-up of the face, the camera pulls back to full body, then it performs a cute K-pop girl-group dance with confident deadpan expression, lip-syncing. Static camera after the pull-back.",
       ["seedance25", "klingomni"], "Seedance 2.5 레퍼런스→영상: 원하는 댄스 영상(내 안무 촬영본)을 video ref로, 음악을 audio ref로 넣으면 동작 복제. Pollo의 Motion Control 기능도 대안",
       tr=("hblur", 0.2)),
     s(2, 17.57, 19.27, "로고 엔드카드", "그래픽", "로고 줌 인", "흰 배경 중앙 분홍 로고 + 하트", "로고 등장", "꾸이티걸 (그래픽)",
       "음악 끝", "영상 끝", "", "", [], "편집 프로그램에서 로고 이미지 + 스케일 90→100% 키프레임")],
    [], {},
    {"summary": "처음부터 끝까지 댄스곡(LRA 1.0 = 강하게 압축된 팝). -14.2 LUFS / 트루피크 -3.5 dBFS. 원곡 식별 불가 → 재현 시 Suno로 자체 곡 또는 인스타 음원 라이브러리 사용.",
     "cues": [("0.0–17.6", "댄스곡", ""), ("17.6–19.3", "엔드카드 (곡 끝부분)", "")],
     "music_prompt": "Suno v5.5 — bouncy K-pop girl-group dance track, 128 BPM, punchy kick, bright synths, catchy hook with cute chant, 20 seconds",
     "sfx_prompts": [], "voice": "없음 (립싱크만)"},
    [("추천", "Seedance 2.5 ref2video · 17초 · 1080p · refs = [캐릭터 시트 이미지, 안무 참고 영상, 음악]",
      "CapCut을 쓰면 원작과 같은 'AI 댄스' 템플릿으로도 가능. 끝 로고는 편집에서.", "1080p 17초 ≈ 할인 약 400")],
    ["춤 안무 자체는 저작권 대상이 될 수 있음 — 유명 곡 안무를 그대로 쓰면 음원·안무 권리 확인",
     "인스타 'AI 정보' 라벨 켜기"],
    ["캐릭터 전용 '시그니처 안무' 1개를 정해 매번 같은 엔드카드로 끝내면 IP 인지도 상승"])

RANK6 = page(
    6, "DcBMA4hCygd", "부산 여행 브이로그 — 35.4초 · 18비트", "꾸이 꾸동 부산여행♥️",
    [("조회수", "100만"), ("좋아요", "47,337"), ("댓글", "331"), ("업로드", "2026-08-14"), ("길이", "35.37초"),
     ("컷", "27 (자동 감지) · 18개 장면"), ("fps", "30"), ("배경음악", "있음")],
    "KTX → 부산역 → 바다 보이는 횟집 → 할머니의 산낙지 → 밀면 → 해수욕장 튜브 → 밤바다 불꽃놀이 → 불꽃 '김꾸이 사랑해♥'. 여행 브이로그 문법 그대로.",
    "평균 1.3초의 빠른 브이로그 편집. 해수욕장·모래사장 구간은 0.2~0.7초 컷이 몰려 있어 아래 장면은 편집 컷이 아닌 '장면 단위(비트)'로 묶었습니다.",
    [("0–5초", "여행 출발 훅", "KTX 좌석 + '언니 우리 부산 가는 거야?' → 목적지·동반자(꾸동)를 1초에."),
     ("5–19초", "부산 먹킷리스트", "부산역 → 횟집 → 산낙지 → 밀면. 지역 명물 체크리스트 = 부산 관련 검색·저장 유도."),
     ("9.1–11.3초", "현지인 할머니", "사람 배우(AI) '이것도 한번 먹어보세요' → 정감."),
     ("19–25초", "빠른 해변 몽타주", "튜브·파도·아이들 — 0.5초 컷으로 에너지 최고조."),
     ("25–35.4초", "밤·불꽃 감성 엔딩", "스파클러 → '이쁘다~' → 모래 '꾸이꾸이' → 불꽃 '김꾸이 사랑해♥'. 팬 서비스 엔딩으로 댓글·공유.")],
    [s(1, 0.0, 0.97, "KTX 투샷", "MS", "고정", "두 캐릭터 좌석에 나란히, 뒤 좌석 헤드커버", "창밖 보며 앉아 있음",
       "언니 우리 부산가는거야?", "'꾸이'", "하드컷",
       f"{CH} and [CHARACTER_2] (black-and-white) wearing tiny travel harnesses, sitting side by side on blue high-speed train seats with white headrest covers, eye level, 35mm",
       "They sit and look around excitedly. Static camera.", ["klingomni", "seedance25"]),
     s(2, 0.97, 2.5, "출발 선언 CU", "MCU", "고정", "캐릭터 중앙", "고개 끄덕", "어디 한번 출발해볼까?", "'꾸이'", "하드컷",
       f"medium close-up of {CH} with a pink harness sitting on a train seat, confident face", "It nods and squeaks. Static camera.",
       ["klingomni", "seedance25"]),
     s(3, 2.5, 4.93, "좌석 투샷", "MS", "고정", "1번과 같은 구도", "둘이 졸거나 창밖을 봄", "없음", "기차 소음", "하드컷", "", "They doze off together. Static camera.", ["klingomni"]),
     s(4, 4.93, 6.57, "부산역 광장", "WS", "고정", "부산역 건물 배경, 캐릭터 둘 전경", "걸어감",
       "밥부터 먼저 먹을까? / 배고파 배고파 배고파", "'꾸이 꾸이'", "하드컷",
       f"wide shot of {CH} and [CHARACTER_2] walking on the plaza in front of a big glass train station building with a Korean station sign, travelers in the background, daylight",
       "They waddle forward toward the camera. Static camera.", ["klingomni", "seedance25"], "역 간판 등 실제 지명은 문제없음"),
     s(5, 6.57, 9.13, "바다 보이는 횟집", "MS", "고정", "창밖 바다·섬, 테이블 위 회·쌈채소", "젓가락으로 회를 먹음",
       "없음", "식당 소리", "하드컷",
       f"{CH} and [CHARACTER_2] at a seaside Korean raw-fish restaurant table with sliced sashimi, lettuce, chili sauce, a big window showing the blue sea and islands",
       "They pick up sashimi with chopsticks and chew happily. Static camera.", ["klingomni", "seedance25"]),
     s(6, 9.13, 11.3, "할머니의 한 접시", "MS", "고정", "사람 할머니 중앙, 접시가 하단", "할머니가 접시를 테이블에 내려놓음",
       "이것도 한번 먹어보세요", "할머니 한국어 대사", "하드컷",
       "medium shot of a kind elderly Korean woman in a black apron over a patterned blouse at a seaside restaurant, serving a plate of chopped live octopus with sesame, warm smile",
       "She places the plate on the table and says in Korean '이것도 한번 먹어보세요'. Static camera.", ["veo31", "seedance25"], "한국어 대사 → Veo 3.1"),
     s(7, 11.3, 12.57, "산낙지 인서트", "CU", "고정", "접시 가득", "꿈틀거리는 낙지", "없음", "", "하드컷",
       "close-up of a white plate of chopped live octopus with sesame seeds and sesame oil, wriggling", "The octopus pieces wriggle slightly.", ["minimaxh3", "hailuo23"]),
     s(8, 12.57, 13.9, "반짝 눈 리액션", "MS", "고정", "두 캐릭터 + 전경 접시", "눈이 커지며 웃음", "없음", "'꾸이!'", "하드컷", "",
       "Both characters stare at the plate with wide sparkling eyes and grin. Static camera.", ["klingomni"]),
     s(9, 13.9, 16.03, "밀면집", "MS", "고정", "두 캐릭터가 밀면 그릇 뒤, 배경 식당 손님", "면을 후루룩", "없음", "후루룩", "하드컷",
       f"{CH} and [CHARACTER_2] slurping cold wheat noodles (milmyeon) from steel bowls with egg halves and cucumber, kimchi and pickled radish on the side, busy local restaurant",
       "They slurp noodles simultaneously. Static camera.", ["klingomni", "seedance25"]),
     s(10, 16.03, 17.77, "겨자 뿌리기 CU", "CU", "고정", "캐릭터 얼굴 좌상, 노란 겨자통이 중앙", "겨자를 짜서 면 위에",
       "없음", "짜는 소리", "하드컷", "", "It squeezes a yellow mustard bottle onto the noodles, deadpan. Static camera.", ["klingomni"]),
     s(11, 16.03 + 1.74, 19.0, "다시 후루룩", "MS", "고정", "9번과 같은 구도", "면 흡입", "없음", "후루룩", "하드컷", "", "They slurp again.", ["klingomni"]),
     s(12, 19.0, 25.0, "해수욕장 튜브 몽타주", "WS 다수", "0.2~0.7초 컷 여러 개", "파도·광안대교·아이들", "튜브 타고 파도를 넘음",
       "없음", "파도·웃음", "하드컷",
       f"{CH} and [CHARACTER_2] floating on a blue polka-dot swim ring over big waves at a crowded Korean beach with a suspension bridge and high-rise buildings, children splashing nearby, sunny",
       "Waves lift the swim ring, splashes, kids laughing around. Handheld energetic camera.", ["minimaxh3", "seedance25"], "물·파도 물리 → MiniMax H3"),
     s(13, 25.0, 25.7, "스파클러 인서트", "CU", "고정", "밤바다 보케 + 불꽃", "스파클러 타오름", "없음", "지지직", "하드컷",
       "close-up of a sparkler burning at night on a beach, bokeh city lights of a suspension bridge", "Sparks fly.", ["hailuo23", "minimaxh3"]),
     s(14, 25.7, 26.93, "'이쁘다~'", "MCU", "고정", "캐릭터 얼굴, 밤 배경 보케", "황홀한 표정", "이쁘다~~~", "'꾸이'", "하드컷", "",
       "It gazes at the sparkler with a dreamy face. Static camera.", ["klingomni"]),
     s(15, 26.93, 29.23, "모래사장 술래잡기", "MS 다수", "빠른 컷", "모래사장, 밤", "쫓고 쫓기기", "나 잡아봐라! / 장난치지마라!",
       "'꾸이 꾸이'", "하드컷", "", "They chase each other on the sand at night, playful. Handheld.", ["klingomni"]),
     s(16, 29.23, 31.7, "모래 글씨", "WS", "고정", "모래에 '꾸이꾸이' 글씨가 하단, 두 캐릭터 위", "모래 위 글씨 앞에 앉음",
       "(모래 글씨 '꾸이꾸이')", "파도", "하드컷",
       f"{CH} and [CHARACTER_2] sitting on night beach sand behind a word written in the sand, a lit suspension bridge on the horizon",
       "Waves glimmer in the background. Static camera.", ["seedance25"], "글씨는 영상 모델이 틀리기 쉬움 → 편집 그래픽으로 얹기"),
     s(17, 31.7, 33.43, "불꽃 발사", "WS", "고정", "광안대교 위 불꽃, 전경에 작은 두 캐릭터 뒷모습", "불꽃이 솟음", "없음", "펑", "하드컷",
       "wide shot of fireworks launching over a lit suspension bridge at night, two tiny characters seen from behind on the beach", "Fireworks shoot up and burst.", ["minimaxh3", "omni11"]),
     s(18, 33.43, 35.37, "불꽃 '김꾸이 사랑해♥'", "그래픽", "고정", "하늘 가득 불꽃 얼굴 + 글씨 + 하트", "불꽃 글씨 완성", "김꾸이 사랑해 ♥ (불꽃 그래픽)",
       "불꽃 소리", "영상 끝", "", "", [], "편집에서 불꽃 파티클 + 글씨 애니메이션(AE: Saber/Trapcode, CapCut 불꽃 텍스트)")],
    [ev(0.4, 0.97, "언니 우리 부산가는거야?", "Are we going to Busan?"), ev(1.1, 2.5, "어디 한번 출발해볼까?", "Shall we go?"),
     ev(4.95, 5.7, "밥부터 먼저 먹을까?", "Should we eat first?"), ev(5.75, 6.55, "배고파 배고파 배고파", "I'm so hungry!"),
     ev(9.5, 11.25, "이것도 한번 먹어보세요", "Try this one too!"), ev(25.9, 26.9, "이쁘다~~~", "So pretty~~~"),
     ev(27.0, 28.0, "나 잡아봐라!", "Catch me if you can!"), ev(28.0, 29.2, "장난치지마라!", "Stop messing around!")],
    {"kr_size": 60, "en_size": 34, "kr_y": 0.741, "en_dy": 0.038, "jp_dy": 0.06, "jp_size": 30, "outline": 2.4, "shadow": 1.8},
    {"summary": "배경음악이 처음부터 끝까지 깔림(무음 0). -14.5 LUFS / LRA 9.5 / 트루피크 0.0 dBFS. 캐릭터 '꾸이' 소리 + 할머니 한국어 대사. Whisper의 영어 문장은 음악 위 오인식이라 제외.",
     "cues": [("0–19", "밝은 여행 BGM + '꾸이'", ""), ("9.7–11.3", "할머니: '이것도 한번 먹어 보세요'", "덕킹"),
              ("19–25", "BGM 고조 + 파도·웃음", ""), ("25–35.4", "감성 BGM + 불꽃", "")],
     "music_prompt": "Suno v5.5 — cheerful summer travel vlog pop, 115 BPM, acoustic guitar, claps, bright synth, turns warm and emotional after 25 seconds for a night-beach fireworks ending, 36 seconds, instrumental",
     "sfx_prompts": ["ocean waves crashing with children laughing on a busy beach, 6 seconds", "fireworks launching and bursting over the sea at night, 3 seconds"],
     "voice": "캐릭터 = '꾸이'. 할머니 = Veo 3.1 네이티브 한국어 또는 TTS."},
    [("추천 조합", "캐릭터 컷 = Kling v3 Omni(레퍼런스 2장) · 할머니 = Veo 3.1 · 파도/불꽃 = MiniMax H3 · 산낙지 인서트 = Hailuo 2.3 · 마지막 불꽃 글씨 = 편집 그래픽",
      "브이로그는 컷이 많으니 장면당 5초 생성 후 필요한 0.5~2초만 사용.", "약 18컷 × 20~48 + 키프레임 ≈ 약 600~900")],
    ["실제 지명(부산역·광안대교)은 문제없음. 식당 간판·상호는 가상으로", "인스타 'AI 정보' 라벨 켜기"],
    ["지역만 바꿔 '꾸이 전국 여행' 시리즈(제주·강릉·전주)", "마지막 불꽃 글씨를 팔로워 이름 이벤트로 활용"])

RANK7 = page(
    7, "DdJBrq2z8QH", "주인에게 들킨 다이어트 — 32.1초", "돼지 김꾸이 한정선 먹방",
    [("조회수", "43.3만"), ("좋아요", "11,090"), ("댓글", "96"), ("업로드", "2026-09-11"), ("길이", "32.08초"),
     ("샷", "9"), ("fps", "24"), ("배경음악", "있음 + 대사")],
    "몰래 간식(포장 떡) 먹방 → 주인 귀가 '또 먹었지?' → 체중계 1.8kg → '오늘부터 다이어트' → 쳇바퀴. 사람 주인(AI) + 캐릭터 2인극.",
    "처음 1.4초는 분홍 집 외관 + 'GgooiiKim' 로고 = 채널 오프닝. 11.7~21.5초는 한 컷 안에서 초점이 캐릭터→문으로 넘어가는 랙 포커스와 주인 클로즈업 푸시인.",
    [("0–1.4초", "채널 로고 오프닝", "고정 오프닝 = 시리즈 인식."),
     ("1.4–11.7초", "몰래 먹방", "포장된 떡을 까서 먹음 → '한정선 맛있다ㅠㅠ'. 브랜드 협찬(PPL) 형식으로 보임."),
     ("11.7–21.5초", "주인 등장 = 갈등", "'다녀왔어~' → '아니, 또 먹었지?' → '아니! 몰라!' → '입이 완전 하얗잖아!' 반려동물 주인 공감."),
     ("21.5–28.4초", "숫자 펀치라인", "체중계 1.8kg 인서트 → '어? 1.8킬로?!' → '같이 다이어트야!'"),
     ("28.4–32.1초", "비명 + 쳇바퀴", "충격 비명 클로즈업 → 쳇바퀴 뛰기 = 벌칙 엔딩.")],
    [s(1, 0.0, 1.38, "채널 오프닝", "WS", "고정", "분홍 2층 집 외관 중앙, 로고 스티커", "로고 등장", "GgooiiKim 로고(그래픽)", "징글", "하드컷",
       "a pastel pink two-story suburban house with a pink gate on a sunny street, wide shot", "Static shot; add the channel logo in editing.", ["omni11"], "로고는 편집 그래픽"),
     s(2, 1.38, 11.67, "몰래 떡 먹방", "MS", "고정", "캐릭터 중앙, 분홍 소파 배경, 유리 테이블 위 포장 떡들", "포장을 풀어 떡을 먹음 → 우는 듯 감동",
       "한정선 맛있다ㅠㅠ (10.2초~)", "'꾸이' + 부스럭", "하드컷",
       f"{CH} sitting on a glass coffee table in a girly pink living room (pink velvet sofa, heart pillows, warm lamps), surrounded by traditional Korean rice-cake gift packages wrapped in colorful paper and cloth",
       "It unwraps a package and eats a white rice cake, crumbs of white powder on its lips, then looks emotional. Static camera.", ["klingomni", "seedance25"]),
     s(3, 11.67, 21.54, "주인 귀가 → 추궁", "MS→CU", "랙 포커스 + 푸시인", "전경 캐릭터(흐림) → 뒤 문에서 주인 등장 → 주인 클로즈업",
       "주인이 들어와 캐릭터에게 다가와 추궁, 캐릭터 발뺌", "다녀왔어~ / 아니, 또 먹었지? / 아니! 몰라! / 입이 완전 하얗잖아!",
       "주인 한국어 대사 + '꾸이'", "하드컷",
       "a young woman with long blonde wavy hair, bangs, pearl necklace, black cardigan and zebra-print mini dress entering a pink room through a door, a guinea-pig-like character blurred in the foreground next to rice-cake packages",
       "Rack focus from the character to the woman entering; she walks in saying '다녀왔어~', leans in close and scolds '아니, 또 먹었지?'. The character squeaks back. Slow push-in.", ["veo31", "klingomni"], "사람 대사·연기 → Veo 3.1"),
     s(4, 21.54, 24.17, "체중계 올리기", "MS", "고정", "분홍 퍼 쿠션 위 체중계 중앙, 뒤에 주인", "주인이 캐릭터를 체중계에 올림",
       "자, 체중계에 올라가 봐.", "주인 대사", "하드컷", "", "The woman places the character on a pink kitchen scale on a fluffy pink cushion.", ["klingomni", "veo31"]),
     s(5, 24.17, 25.0, "1.8kg 인서트", "ECU", "고정", "저울 숫자창 가득", "1.8kg 표시", "없음 (화면 숫자 1.8kg)", "삑", "하드컷",
       "extreme close-up of a pink digital kitchen scale display reading 1.8 kg, fluffy fur at the top of the frame", "The digits settle on 1.8 kg.", ["hailuo23"], "숫자는 편집에서 합성하는 게 안전"),
     s(6, 25.0, 28.4, "'1.8킬로?!'", "MS", "고정", "주인 중앙, 전경 체중계 위 캐릭터", "주인 경악 → 다이어트 선언",
       "어? 1.8킬로?! / 오늘부터 같이 다이어트야!", "주인 대사", "하드컷", "",
       "The woman gasps '어? 1.8킬로?!' then declares '오늘부터 같이 다이어트야!'", ["veo31"]),
     s(7, 28.4, 29.04, "비명 클로즈업", "CU", "고정", "캐릭터 얼굴 가득, 입 크게", "충격 비명", "없음", "'꾸이이이이!' 비명", "하드컷", "",
       "The character screams in shock with its mouth wide open, buck teeth visible. Static.", ["klingomni", "seedance25"]),
     s(8, 29.04, 32.08, "쳇바퀴 벌칙", "FS", "고정", "하단 중앙 분홍 쳇바퀴 속 캐릭터, 뒤에 팔짱 낀 주인", "쳇바퀴를 달림",
       "오늘부터 매일이야", "'꾸이이이' + 바퀴 소리", "영상 끝",
       f"{CH} running inside a pink hamster exercise wheel on a fluffy rug, the blonde woman standing behind with arms crossed", "It runs desperately in the wheel while she watches sternly. Static camera.", ["klingomni", "seedance25"])],
    [ev(10.2, 11.6, "한정선 맛있다ㅠㅠ", "Han Jeong-seon is so good", "ハンジョンソン おいしい"),
     ev(16.0, 17.75, "다녀왔어~", "I'm back~", "ただいま〜"), ev(17.75, 19.25, "아니, 또 먹었지?", "You ate again, didn't you?", "また食べたでしょ？"),
     ev(19.25, 19.75, "아니! 몰라!", "No! I don't know!", "違う！知らない！"),
     ev(19.75, 21.5, "입이 완전 하얗잖아!", "Your mouth is all white!", "口が真っ白じゃん！"),
     ev(21.6, 23.6, "자, 체중계에 올라가 봐.", "Okay, get on the scale.", ""),
     ev(25.25, 27.0, "어? 1.8킬로?!", "What? 1.8 kg?!", "えっ？1.8キロ！？"),
     ev(27.25, 28.3, "오늘부터 같이 다이어트야!", "We're going on a diet together starting today!", ""),
     ev(29.25, 30.5, "오늘부터 매일이야", "Every day from now on", "")],
    {"kr_size": 58, "en_size": 34, "kr_y": 0.667, "en_dy": 0.036, "jp_dy": 0.062, "jp_size": 30, "outline": 2.4, "shadow": 1.8},
    {"summary": "대사 중심(LRA 22.5 = 조용한 먹방 → 큰 대사·비명으로 폭이 매우 넓음). -14.3 LUFS / 트루피크 -0.6. 주인 대사는 한국어, 캐릭터는 '꾸이'·비명.",
     "cues": [("0–1.4", "오프닝 징글", ""), ("1.4–11.7", "부스럭·먹는 소리", ""), ("16.2–28.1", "주인 대사 5줄", ""), ("28.1–32", "'꾸이이이이' 비명 + 쳇바퀴", "")],
     "music_prompt": "", "sfx_prompts": ["crinkling paper gift wrap being opened, 2 seconds", "small plastic hamster wheel spinning fast, 3 seconds"],
     "voice": "주인 = Veo 3.1 네이티브 대사 또는 ElevenLabs v3 젊은 여성 TTS. 캐릭터 비명은 녹음 후 음정 올리기."},
    [("추천 조합", "캐릭터 컷 = Kling v3 Omni · 주인 대사 컷 = Veo 3.1 · 1.8kg 숫자 = 편집 합성",
      "사람 배우 얼굴을 컷마다 같게 → 사람도 캐릭터 시트처럼 레퍼런스 이미지 1장 만들어 사용.", "약 9컷 × 20~48 + 키프레임 ≈ 약 350~550")],
    [LABEL + " ('한정선'은 실제 떡 브랜드로 보임 — 협찬 표기 여부 확인)", "⚠️ 사람 배우는 실존 인물을 닮지 않게", "인스타 'AI 정보' 라벨 켜기"],
    ["'주인 vs 캐릭터' 2인극 시리즈화(다이어트·청소·용돈)", "1.8kg 같은 숫자 펀치라인을 매 화 고정 장치로"])

RANK8 = page(
    8, "Dc4wWd3zOfM", "마카롱 우유 말먹 — 20초", "마카롱 우유 말먹 먹방 꾸이",
    [("조회수", "36.6만"), ("좋아요", "19,756"), ("댓글", "200"), ("업로드", "2026-09-05"), ("길이", "20.03초"),
     ("샷", "6"), ("fps", "30"), ("배경음악", "없음 (ASMR)")],
    "시리얼처럼 마카롱에 우유를 부어 먹는 '말먹'. 와이드 → 붓기 인서트 2컷 → 먹방 → 매크로 한입 → 입가 클로즈업.",
    "고정 카메라 6컷. 인서트(붓기·매크로)와 캐릭터 컷을 번갈아 음식 광고 리듬으로 편집. 무음 구간이 많아 소리보다 화면 중심.",
    [("0–2.7초", "메뉴 한 줄 훅", "'오늘은 마카롱 우유 말먹이다 꾸이!' = 이상한 조합이 궁금증 유발."),
     ("2.7–6.3초", "붓기 인서트 2컷", "마카롱 쏟기·우유 붓기 = 만족감(Satisfying) 영상 문법."),
     ("6.3–14.5초", "먹방 + 웃음", "숟가락으로 떠먹고 '히힛'."),
     ("14.5–17.3초", "매크로 한입", "우유 떨어지는 마카롱 슬로 매크로 = 음식 포르노."),
     ("17.3–20초", "입가 클로즈업 엔딩", "우유 묻은 입술 + '입에서 사르르 녹는다 꾸이…'")],
    [s(1, 0.0, 2.73, "테이블 와이드", "MS", "고정", "캐릭터 중앙, 좌측 마카롱 접시·가운데 유리볼·우측 우유통", "카메라 응시",
       "오늘은 마카롱 우유 말먹이다 꾸이!", "'꾸이 꾸이?'", "하드컷",
       f"{CH} sitting at a white table with a plate of colorful macarons, an empty glass bowl and a milk jug, {YELLOW_WALL}, medium shot, eye level, 50mm",
       "It looks at the camera and squeaks curiously. Static camera.", ["klingomni", "seedance25"]),
     s(2, 2.73, 4.1, "마카롱 쏟기", "인서트 CU", "고정", "유리볼 중앙, 위에서 앞발+접시", "마카롱을 볼에 쏟음", "없음", "달그락", "하드컷",
       "close-up of tiny furry paws tipping a plate of pastel macarons into an empty glass bowl on a white table", "Macarons tumble into the bowl.", ["minimaxh3", "klingomni"]),
     s(3, 4.1, 6.33, "우유 붓기", "인서트 CU", "고정", "볼 중앙, 좌상단 우유통", "우유를 부음", "없음", "콸콸", "하드컷",
       "close-up of furry paws pouring milk from a white milk jug (fictional label) into a glass bowl full of macarons", "Milk pours and splashes around the macarons, satisfying.", ["minimaxh3", "veo31"], LABEL + " (매일우유)"),
     s(4, 6.33, 14.47, "먹방", "MS", "고정", "캐릭터 중앙, 볼이 하단", "숟가락으로 떠먹고 웃음", "없음", "'히힛' + 숟가락", "하드컷", "",
       "It eats milk-soaked macarons with a small spoon, giggles 'hihit'. Static camera.", ["klingomni", "seedance25"]),
     s(5, 14.47, 17.33, "매크로 한입", "ECU 매크로", "고정", "숟가락 위 마카롱이 중앙, 뒤 흐린 캐릭터", "우유가 뚝뚝 떨어짐", "없음", "", "하드컷",
       "macro shot of a clear spoon lifting a pink macaron dripping with milk above a bowl of colorful macarons, blurred furry character behind", "Milk drips slowly from the macaron, slow motion.", ["veo31", "minimaxh3"]),
     s(6, 17.33, 20.03, "입가 클로즈업", "ECU", "고정", "코·입이 화면 가득", "우유 묻은 입술로 씹으며 미소", "입에서 사르르 녹는다 꾸이...",
       "", "영상 끝", "extreme close-up of [CHARACTER]'s snout and human-like lips with a drop of milk, chewing", "It chews slowly and smiles with milk on its lips.", ["klingomni"])],
    [ev(0.3, 2.7, "오늘은 마카롱 우유 말먹이다 꾸이!", "Today, we're having macarons with milk!", ""),
     ev(18.5, 20.0, "입에서 사르르 녹는다 꾸이...", "It just melts in my mouth...", "口の中でとろ〜っと溶ける…")],
    {"kr_size": 56, "en_size": 32, "kr_y": 0.63, "en_dy": 0.045, "jp_dy": 0.068, "jp_size": 30, "outline": 2.4, "shadow": 1.8},
    {"summary": "배경음악 없음, 무음 구간 다수(0.1초 단위 21곳). '꾸이 꾸이?'·'흐음?'·'히힛' + 붓는 소리. -14.8 LUFS / 트루피크 +0.9 (넘침 → -1 dBTP).",
     "cues": [("0–1.6", "'꾸이 꾸이?'", ""), ("2.7–6.3", "쏟기·붓기 소리", ""), ("6.3–14.5", "숟가락·'히힛'", "")],
     "music_prompt": "", "sfx_prompts": ["milk pouring into a glass bowl of macarons, splashing, 2 seconds"], "voice": "영상 모델 오디오 또는 녹음 후 음정 올리기."},
    [("추천 조합", "캐릭터 컷 = Kling v3 Omni · 붓기·매크로 = MiniMax H3 / Veo 3.1", "음식만 바꾸기 쉬운 가장 저비용 포맷.", "약 6컷 ≈ 약 200~300")],
    [LABEL + " (매일우유 라벨)", "인스타 'AI 정보' 라벨 켜기"],
    ["'OO 말먹' 시리즈: 초코파이·약과·붕어빵에 우유"])

RANK9 = page(
    9, "DdWBbk0Pcci", "존잘 오빠는 스티커 — 42.2초", "김꾸이한테 괜히 남소받음",
    [("조회수", "20.2만"), ("좋아요", "7,226"), ("댓글", "55"), ("업로드", "2026-09-16"), ("길이", "42.17초"),
     ("샷", "15"), ("fps", "30"), ("배경음악", "있음")],
    "꾸이가 '존잘 오빠 집에서 카레 먹었다'며 주인을 소개팅시켜 줌 → 설레며 방문 → 오빠는 2D 만화 캐릭터 → 알고 보니 종이 스티커(등신대). '미안하다 꾸이…'",
    "실사 주인·실사 집 + 2D 웹툰 남자의 이질감이 핵심 개그. 28초부터 남자만 만화체, 36초에 종이처럼 벗겨지며 반전.",
    [("0–12.4초", "소개팅 떡밥", "'존잘 오빠 집에서 카레' → '주인도 소개해줄게!' 호기심 + 연애 떡밥."),
     ("12.4–21.8초", "설렘 빌드업", "'갈래 갈래!' → 복도 → 문 열기(POV) = 기대감."),
     ("21.8–27.5초", "반전 ①", "실사 부엌의 남자 → 주인 '진짜 개잘생겼잖아!'"),
     ("28.1–37.5초", "이질감", "남자만 2D 웹툰 그림체 → '엥 이게 뭐지…' → 종이처럼 벗겨짐."),
     ("37.5–42.2초", "반전 ② + 사과", "등신대 스티커를 들고 '스티커잖아…' → 꾸이 '미안하다 꾸이…' = 2단 반전 개그.")],
    [s(1, 0.0, 0.33, "화장대 투샷", "MS", "고정", "캐릭터 전경 중앙, 뒤 주인", "", "없음", "", "하드컷", "", "", ["klingomni"]),
     s(2, 0.33, 1.7, "입 클로즈업 고백", "ECU", "고정", "입이 화면 가득", "말함", "주인 나 저번에 존잘 오빠 집에서", "'꾸이'", "하드컷",
       "extreme close-up of [CHARACTER]'s human-like lips speaking", "Its lips move as it talks.", ["klingomni"]),
     s(3, 1.7, 12.43, "화장대 대화", "MS", "고정", "캐릭터 전경 중앙(테이블 위), 뒤 주인 얼굴, 분홍 공주 방",
       "캐릭터 자랑 → 주인 놀람 → 제안 → 설렘",
       "카레 얻어먹고 왔어~! 또 가고싶어 / 엥, 존잘 오빠 집에서 카레 먹고 왔다고? / 주인도 소개해줄게! 같이 가자! / 헐, 나도 소개해 준다고?",
       "'꾸이' + 주인 대사", "하드컷",
       f"{CH} sitting on a vanity table in a pink princess bedroom with lace curtains, a young woman with long blonde hair and bangs behind it leaning in, medium shot",
       "They chat: the character brags, the woman reacts surprised then excited. Static camera.", ["veo31", "klingomni"]),
     s(4, 12.43, 15.0, "'갈래 갈래!'", "MS", "핸드헬드", "주인이 캐릭터를 들어 올림", "들고 신나서 나감", "갈래 갈래!", "주인 대사", "하드컷", "",
       "She lifts the character happily and hurries off. Handheld.", ["veo31", "klingomni"]),
     s(5, 15.0, 17.83, "아파트 복도", "MS 뒤따라가기", "팔로우", "주인 뒷모습, 손바닥 위 캐릭터", "복도를 걸어감",
       "여기야? 진짜 존잘 맞아? / 진짜 존잘이다 꾸이", "대사", "하드컷", "", "She walks down an apartment hallway holding the character in her palm. Follow shot.", ["veo31", "klingomni"]),
     s(6, 17.83, 18.77, "손바닥 위 의기양양", "CU", "고정", "손바닥 위 캐릭터 중앙", "우쭐한 미소", "없음", "", "하드컷", "", "Smug grin in her palm.", ["klingomni"]),
     s(7, 18.77, 21.8, "문 열기 POV", "POV", "핸드헬드", "문 손잡이 → 틈으로 실내", "문을 엶", "없음", "문 소리", "하드컷", "", "POV: she opens the front door slowly.", ["veo31"]),
     s(8, 21.8, 24.93, "부엌의 남자", "WS", "고정", "노을 부엌, 요리하는 남자 중앙", "남자가 요리 중", "없음", "지글", "하드컷",
       "wide shot of a stylish apartment kitchen at golden hour, a tall young man with black wavy hair in a black tank top cooking at a stove", "He stir-fries in a wok. Static camera.", ["veo31", "omni11"]),
     s(9, 24.93, 26.33, "주인 경악", "CU", "고정", "주인 얼굴 가득", "눈 커짐", "잠깐, 진짜 개잘생겼잖아!", "대사", "하드컷", "", "Her eyes widen in shock.", ["veo31"]),
     s(10, 26.33, 27.53, "'거봐'", "CU", "고정", "손바닥 위 캐릭터", "자랑", "거봐, 존잘 맞지 꾸이?", "'꾸이'", "하드컷", "", "It says proudly.", ["klingomni"]),
     s(11, 27.53, 28.1, "들어가는 뒷모습", "MS", "고정", "주인 뒷모습", "", "없음", "", "하드컷", "", "", ["veo31"]),
     s(12, 28.1, 31.3, "2D 오빠와 투샷", "MS", "고정", "좌 주인(실사), 우 남자(2D 웹툰 그림체)", "주인이 애교",
       "어머~ 오빠♡", "대사", "하드컷",
       "a real blonde woman holding a guinea-pig-like character next to a tall man drawn in flat 2D Korean webtoon (manhwa) style, black tank top, in a real kitchen — mixed media",
       "She flirts; the 2D man stays stiff. Static camera.", ["seedance25", "klingomni"], "실사+2D 혼합은 이미지 단계에서 합성(Nano Banana Pro)해 첫 프레임으로"),
     s(13, 31.3, 32.23, "가슴 쿡 인서트", "ECU", "고정", "손가락이 2D 가슴을 누름", "", "없음", "", "하드컷", "", "Her finger pokes his flat drawn chest.", ["klingomni"]),
     s(14, 32.23, 37.53, "요리 투샷 → 벗겨짐", "MS", "고정", "남자 좌, 주인 우", "이상함을 느낌 → 남자 머리가 종이처럼 벗겨짐",
       "엥 이게 뭐지...", "종이 바스락", "하드컷", "", "The man's head peels like a paper sticker. Static camera.", ["seedance25"]),
     s(15, 37.53, 42.17, "스티커 반전", "MS", "고정", "주인이 종이 등신대를 들어 올림", "허탈",
       "어, 잠깐만. 스티커잖아..... / 미안하다 꾸이...", "대사", "영상 끝", "", "She lifts the flat cardboard cutout of the man; the character looks guilty.", ["seedance25", "veo31"])],
    [ev(0.4, 1.7, "주인 나 저번에 존잘 오빠 집에서", "Had curry at a hottie's lol."),
     ev(2.0, 4.7, "카레 얻어먹고 왔어~! 또 가고싶어", "Had curry at a hottie's lol."),
     ev(4.75, 8.25, "엥, 존잘 오빠 집에서 카레 먹고 왔다고?", ""), ev(8.25, 10.0, "주인도 소개해줄게! 같이 가자!", ""),
     ev(10.5, 12.25, "헐, 나도 소개해 준다고?", ""), ev(12.5, 13.3, "갈래 갈래!", "I'm so down!"),
     ev(15.0, 17.0, "여기야? 진짜 존잘 맞아?", ""), ev(17.0, 17.8, "진짜 존잘이다 꾸이", "Yep, he's hot."),
     ev(25.0, 26.3, "잠깐, 진짜 개잘생겼잖아!", "Wait—he's actually so fine!"),
     ev(26.4, 27.5, "거봐, 존잘 맞지 꾸이?", "Told you—he's fine"), ev(28.7, 31.0, "어머~ 오빠♡", "Well, hello, handsome♡"),
     ev(33.2, 35.2, "엥 이게 뭐지...", "what is this?"), ev(38.5, 40.8, "어, 잠깐만. 스티커잖아.....", "Wait—he's literally a sticker!"),
     ev(41.0, 42.17, "미안하다 꾸이...", "I'm sorry...")],
    {"kr_size": 46, "en_size": 28, "kr_y": 0.735, "en_dy": 0.026, "jp_dy": 0.05, "jp_size": 26, "outline": 2, "shadow": 1.5},
    {"summary": "배경음악 + 대사. 캐릭터는 '꾸이', 주인은 한국어 대사. (세부 수치는 audio 섹션 이미지 참고)",
     "cues": [("0–12.4", "대화 + 잔잔한 BGM", ""), ("21.8–27.5", "설렘 효과음/음악 고조", ""), ("36–42", "반전 후 허탈한 음악", "")],
     "music_prompt": "Suno v5.5 — playful rom-com K-drama style BGM, 100 BPM, pizzicato strings and light piano, a romantic swell at 22 seconds, a comedic deflating ending at 37 seconds, 42 seconds, instrumental",
     "sfx_prompts": ["a paper sticker being peeled off slowly, 2 seconds"], "voice": "주인 = Veo 3.1 또는 TTS, 캐릭터 = '꾸이'."},
    [("추천 조합", "실사 주인 컷 = Veo 3.1 · 캐릭터 = Kling v3 Omni · 2D 남자 혼합 컷 = 이미지에서 합성 후 Seedance 2.5",
      "반전 컷(벗겨짐)은 편집으로도 가능: 남자를 투명 PNG로 얹고 페이지 컬(Page Curl) 전환.", "약 15컷 ≈ 약 500~800")],
    ["⚠️ 실존 웹툰 캐릭터를 닮게 그리지 말 것(저작권)", "⚠️ 사람 배우는 실존 인물을 닮지 않게", "인스타 'AI 정보' 라벨 켜기"],
    ["'꾸이의 소개팅 주선' 시리즈 — 매번 다른 반전(마네킹·로봇·인형)"])

RANK10 = page(
    10, "DdUHHhET23I", "꾸이·또리 키링 제작 — 17.9초", "꾸이와 또리의 만남 · 키링",
    [("조회수", "12.5만"), ("좋아요", "7,036"), ("댓글", "100"), ("업로드", "2026-09-16"), ("길이", "17.87초"),
     ("샷", "9"), ("fps", "30"), ("배경음악", "있음 (노래)")],
    "손으로 만든 점토 키링 제작 과정. 손글씨 '꾸이/또리' 타이틀 → 턴테이블 + 실제 모델 PIP → 빚기·색칠 → '???' → 'happy ending' → 완성 키링.",
    "AI 영상이 아니라 실제 손 제작 영상처럼 보임(공동 계정 @ddolleekim 태그). 굿즈·팬아트 포맷 — 캐릭터 IP 확장 사례.",
    [("0–1.6초", "손글씨 타이틀", "'꾸이 / 또리' 낙서 = 팬심·수공예 감성."),
     ("1.6–7.4초", "PIP 비교", "완성품 옆 작은 창에 실제 캐릭터 영상 → '똑같다' 비교 재미."),
     ("7.4–12.3초", "제작 과정", "빚기·색칠 = 공정 영상의 만족감."),
     ("12.3–15.6초", "'???' → 'happy ending'", "낙서 자막으로 감정 전달."),
     ("15.6–17.9초", "완성 컷", "패턴 천 위 완성 키링 + 낙서 = 굿즈 판매·DM 유도.")],
    [s(1, 0.0, 1.6, "손글씨 타이틀", "CU", "고정", "키링 2개 중앙, 좌상 '꾸이'·우하 '또리' 손글씨", "", "꾸이 / 또리 (손글씨 그래픽)", "노래", "하드컷",
       "two small handmade clay guinea-pig keychains hanging from a red cord against a teal background", "", ["hailuo23"], "실제 촬영 권장"),
     s(2, 1.6, 7.37, "턴테이블 + PIP", "WS 부감", "고정", "나무 턴테이블 위 키링 2개, 하단 PIP 창", "키링이 돌아감", "없음(PIP 영상)", "노래", "하드컷", "", "", [], "PIP = 편집에서 작은 창(원본 캐릭터 영상)"),
     s(3, 7.37, 8.27, "빚기", "CU", "고정", "손가락과 흰 점토", "점토를 빚음", "없음", "", "하드컷", "", "", [], "실제 촬영"),
     s(4, 8.27, 10.43, "색칠된 몸통", "CU", "고정", "손가락이 작은 인형을 들고 있음", "", "없음", "", "하드컷", "", "", []),
     s(5, 10.43, 11.37, "붓 색칠", "CU", "고정", "붓·인형", "색칠", "없음", "", "하드컷", "", "", []),
     s(6, 11.37, 12.33, "팔레트", "CU", "고정", "", "", "없음", "", "하드컷", "", "", []),
     s(7, 12.33, 13.53, "'???'", "CU", "고정", "노란 얼굴 인형 + 손글씨 ???", "", "??? (손글씨)", "", "하드컷", "", "", []),
     s(8, 13.53, 15.63, "'happy ending'", "CU", "고정", "키링 2개 + 손글씨", "", "happy ending (손글씨)", "", "하드컷", "", "", []),
     s(9, 15.63, 17.87, "완성 컷", "CU", "고정", "패턴 천 위 키링 + 흰 낙서 테두리", "", "없음(낙서 그래픽)", "노래 끝", "영상 끝", "", "", [])],
    [], {},
    {"summary": "노래(보컬 있는 곡)가 깔림 — 음원 저작권 확인 필요. 대사 없음.",
     "cues": [("0–17.9", "보컬 곡", "")], "music_prompt": "Suno v5.5 — cute lo-fi pop with soft female vocal humming, 100 BPM, 18 seconds",
     "sfx_prompts": [], "voice": "없음"},
    [("추천", "AI보다 실제 촬영(점토 공예) + 손글씨 오버레이. AI로 하려면 Kling v3 Omni로 '손으로 점토 인형 빚기' 인서트",
      "굿즈 판매·공동구매 연결용 영상.", "촬영이면 0")],
    ["⚠️ 배경 노래 음원 권리 확인(인스타 음원 라이브러리 사용 권장)", "타 계정(@ddolleekim) 태그 = 콜라보 — 재현 시 동의 필요"],
    ["팔로워 제작 굿즈 리그램 = 커뮤니티 성장"])

PAGES_4_10 = [RANK4, RANK5, RANK6, RANK7, RANK8, RANK9, RANK10]
